analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true
  exclude:
    - test/*.dart
    - lib/src/model/*.g.dart
