name: keiser_metrics_sdk
version: 5.0.28
description: OpenAPI API client
homepage: https://github.com/KeiserCorp/Keiser.Metrics.SDK.Dart
repository: https://github.com/KeiserCorp/Keiser.Metrics.SDK.Dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: '^4.7.0'
  keiser_metrics_connection: ^0.2.2

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
