name: keiser_metrics_sdk
version: 5.0.15
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: '^4.7.0'
  keiser_metrics_connection: ^0.1.0

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
