// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'facility_display_configuration_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FacilityDisplayConfigurationData _$FacilityDisplayConfigurationDataFromJson(
        Map<String, dynamic> json) =>
    $checkedCreate(
      'FacilityDisplayConfigurationData',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const [
            'facilityId',
            'unit',
            'timeZone',
            'qrCodeEnabled',
            'operatingScheduleEnabled',
            'operatingSchedule',
            'shouldForceExercise',
            'signoutDelay',
            'showReviewScreen',
            'defaultBrightness',
            'machinesEnabled',
            'isTorqueEnabled',
            'dataMode',
            'focusMode'
          ],
        );
        final val = FacilityDisplayConfigurationData(
          facilityId: $checkedConvert('facilityId', (v) => v as num),
          unit: $checkedConvert(
              'unit', (v) => $enumDecode(_$DisplayUnitEnumMap, v)),
          timeZone: $checkedConvert(
              'timeZone', (v) => $enumDecode(_$TimeZoneEnumMap, v)),
          qrCodeEnabled: $checkedConvert('qrCodeEnabled', (v) => v as bool),
          operatingScheduleEnabled:
              $checkedConvert('operatingScheduleEnabled', (v) => v as bool),
          operatingSchedule: $checkedConvert(
              'operatingSchedule',
              (v) => FacilityDisplayOperatingSchedule.fromJson(
                  v as Map<String, dynamic>)),
          shouldForceExercise:
              $checkedConvert('shouldForceExercise', (v) => v as bool),
          signoutDelay: $checkedConvert('signoutDelay', (v) => v as num),
          showReviewScreen:
              $checkedConvert('showReviewScreen', (v) => v as bool),
          defaultBrightness:
              $checkedConvert('defaultBrightness', (v) => v as num),
          machinesEnabled: $checkedConvert('machinesEnabled', (v) => v as bool),
          isTorqueEnabled: $checkedConvert('isTorqueEnabled', (v) => v as bool),
          dataMode: $checkedConvert(
              'dataMode', (v) => $enumDecode(_$DisplayDataModeEnumMap, v)),
          focusMode: $checkedConvert(
              'focusMode', (v) => $enumDecode(_$DisplayFocusModeEnumMap, v)),
          performanceDropOff:
              $checkedConvert('performanceDropOff', (v) => v as num?),
          addedMass: $checkedConvert('addedMass', (v) => v as num?),
          secondsDelay: $checkedConvert('secondsDelay', (v) => v as num?),
        );
        return val;
      },
    );

Map<String, dynamic> _$FacilityDisplayConfigurationDataToJson(
    FacilityDisplayConfigurationData instance) {
  final val = <String, dynamic>{
    'facilityId': instance.facilityId,
    'unit': _$DisplayUnitEnumMap[instance.unit]!,
    'timeZone': _$TimeZoneEnumMap[instance.timeZone]!,
    'qrCodeEnabled': instance.qrCodeEnabled,
    'operatingScheduleEnabled': instance.operatingScheduleEnabled,
    'operatingSchedule': instance.operatingSchedule.toJson(),
    'shouldForceExercise': instance.shouldForceExercise,
    'signoutDelay': instance.signoutDelay,
    'showReviewScreen': instance.showReviewScreen,
    'defaultBrightness': instance.defaultBrightness,
    'machinesEnabled': instance.machinesEnabled,
    'isTorqueEnabled': instance.isTorqueEnabled,
    'dataMode': _$DisplayDataModeEnumMap[instance.dataMode]!,
    'focusMode': _$DisplayFocusModeEnumMap[instance.focusMode]!,
  };

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('performanceDropOff', instance.performanceDropOff);
  writeNotNull('addedMass', instance.addedMass);
  writeNotNull('secondsDelay', instance.secondsDelay);
  return val;
}

const _$DisplayUnitEnumMap = {
  DisplayUnit.metric: 'metric',
  DisplayUnit.imperial: 'imperial',
  DisplayUnit.si: 'si',
};

const _$TimeZoneEnumMap = {
  TimeZone.Africa_Abidjan: 'Africa/Abidjan',
  TimeZone.Africa_Accra: 'Africa/Accra',
  TimeZone.Africa_Addis_Ababa: 'Africa/Addis_Ababa',
  TimeZone.Africa_Algiers: 'Africa/Algiers',
  TimeZone.Africa_Asmara: 'Africa/Asmara',
  TimeZone.Africa_Asmera: 'Africa/Asmera',
  TimeZone.Africa_Bamako: 'Africa/Bamako',
  TimeZone.Africa_Bangui: 'Africa/Bangui',
  TimeZone.Africa_Banjul: 'Africa/Banjul',
  TimeZone.Africa_Bissau: 'Africa/Bissau',
  TimeZone.Africa_Blantyre: 'Africa/Blantyre',
  TimeZone.Africa_Brazzaville: 'Africa/Brazzaville',
  TimeZone.Africa_Bujumbura: 'Africa/Bujumbura',
  TimeZone.Africa_Cairo: 'Africa/Cairo',
  TimeZone.Africa_Casablanca: 'Africa/Casablanca',
  TimeZone.Africa_Ceuta: 'Africa/Ceuta',
  TimeZone.Africa_Conakry: 'Africa/Conakry',
  TimeZone.Africa_Dakar: 'Africa/Dakar',
  TimeZone.Africa_Dar_es_Salaam: 'Africa/Dar_es_Salaam',
  TimeZone.Africa_Djibouti: 'Africa/Djibouti',
  TimeZone.Africa_Douala: 'Africa/Douala',
  TimeZone.Africa_El_Aaiun: 'Africa/El_Aaiun',
  TimeZone.Africa_Freetown: 'Africa/Freetown',
  TimeZone.Africa_Gaborone: 'Africa/Gaborone',
  TimeZone.Africa_Harare: 'Africa/Harare',
  TimeZone.Africa_Johannesburg: 'Africa/Johannesburg',
  TimeZone.Africa_Juba: 'Africa/Juba',
  TimeZone.Africa_Kampala: 'Africa/Kampala',
  TimeZone.Africa_Khartoum: 'Africa/Khartoum',
  TimeZone.Africa_Kigali: 'Africa/Kigali',
  TimeZone.Africa_Kinshasa: 'Africa/Kinshasa',
  TimeZone.Africa_Lagos: 'Africa/Lagos',
  TimeZone.Africa_Libreville: 'Africa/Libreville',
  TimeZone.Africa_Lome: 'Africa/Lome',
  TimeZone.Africa_Luanda: 'Africa/Luanda',
  TimeZone.Africa_Lubumbashi: 'Africa/Lubumbashi',
  TimeZone.Africa_Lusaka: 'Africa/Lusaka',
  TimeZone.Africa_Malabo: 'Africa/Malabo',
  TimeZone.Africa_Maputo: 'Africa/Maputo',
  TimeZone.Africa_Maseru: 'Africa/Maseru',
  TimeZone.Africa_Mbabane: 'Africa/Mbabane',
  TimeZone.Africa_Mogadishu: 'Africa/Mogadishu',
  TimeZone.Africa_Monrovia: 'Africa/Monrovia',
  TimeZone.Africa_Nairobi: 'Africa/Nairobi',
  TimeZone.Africa_Ndjamena: 'Africa/Ndjamena',
  TimeZone.Africa_Niamey: 'Africa/Niamey',
  TimeZone.Africa_Nouakchott: 'Africa/Nouakchott',
  TimeZone.Africa_Ouagadougou: 'Africa/Ouagadougou',
  TimeZone.Africa_PortoMinusNovo: 'Africa/Porto-Novo',
  TimeZone.Africa_Sao_Tome: 'Africa/Sao_Tome',
  TimeZone.Africa_Timbuktu: 'Africa/Timbuktu',
  TimeZone.Africa_Tripoli: 'Africa/Tripoli',
  TimeZone.Africa_Tunis: 'Africa/Tunis',
  TimeZone.Africa_Windhoek: 'Africa/Windhoek',
  TimeZone.America_Adak: 'America/Adak',
  TimeZone.America_Anchorage: 'America/Anchorage',
  TimeZone.America_Anguilla: 'America/Anguilla',
  TimeZone.America_Antigua: 'America/Antigua',
  TimeZone.America_Araguaina: 'America/Araguaina',
  TimeZone.America_Argentina_Buenos_Aires: 'America/Argentina/Buenos_Aires',
  TimeZone.America_Argentina_Catamarca: 'America/Argentina/Catamarca',
  TimeZone.America_Argentina_ComodRivadavia: 'America/Argentina/ComodRivadavia',
  TimeZone.America_Argentina_Cordoba: 'America/Argentina/Cordoba',
  TimeZone.America_Argentina_Jujuy: 'America/Argentina/Jujuy',
  TimeZone.America_Argentina_La_Rioja: 'America/Argentina/La_Rioja',
  TimeZone.America_Argentina_Mendoza: 'America/Argentina/Mendoza',
  TimeZone.America_Argentina_Rio_Gallegos: 'America/Argentina/Rio_Gallegos',
  TimeZone.America_Argentina_Salta: 'America/Argentina/Salta',
  TimeZone.America_Argentina_San_Juan: 'America/Argentina/San_Juan',
  TimeZone.America_Argentina_San_Luis: 'America/Argentina/San_Luis',
  TimeZone.America_Argentina_Tucuman: 'America/Argentina/Tucuman',
  TimeZone.America_Argentina_Ushuaia: 'America/Argentina/Ushuaia',
  TimeZone.America_Aruba: 'America/Aruba',
  TimeZone.America_Asuncion: 'America/Asuncion',
  TimeZone.America_Atikokan: 'America/Atikokan',
  TimeZone.America_Atka: 'America/Atka',
  TimeZone.America_Bahia: 'America/Bahia',
  TimeZone.America_Bahia_Banderas: 'America/Bahia_Banderas',
  TimeZone.America_Barbados: 'America/Barbados',
  TimeZone.America_Belem: 'America/Belem',
  TimeZone.America_Belize: 'America/Belize',
  TimeZone.America_BlancMinusSablon: 'America/Blanc-Sablon',
  TimeZone.America_Boa_Vista: 'America/Boa_Vista',
  TimeZone.America_Bogota: 'America/Bogota',
  TimeZone.America_Boise: 'America/Boise',
  TimeZone.America_Buenos_Aires: 'America/Buenos_Aires',
  TimeZone.America_Cambridge_Bay: 'America/Cambridge_Bay',
  TimeZone.America_Campo_Grande: 'America/Campo_Grande',
  TimeZone.America_Cancun: 'America/Cancun',
  TimeZone.America_Caracas: 'America/Caracas',
  TimeZone.America_Catamarca: 'America/Catamarca',
  TimeZone.America_Cayenne: 'America/Cayenne',
  TimeZone.America_Cayman: 'America/Cayman',
  TimeZone.America_Chicago: 'America/Chicago',
  TimeZone.America_Chihuahua: 'America/Chihuahua',
  TimeZone.America_Coral_Harbour: 'America/Coral_Harbour',
  TimeZone.America_Cordoba: 'America/Cordoba',
  TimeZone.America_Costa_Rica: 'America/Costa_Rica',
  TimeZone.America_Creston: 'America/Creston',
  TimeZone.America_Cuiaba: 'America/Cuiaba',
  TimeZone.America_Curacao: 'America/Curacao',
  TimeZone.America_Danmarkshavn: 'America/Danmarkshavn',
  TimeZone.America_Dawson: 'America/Dawson',
  TimeZone.America_Dawson_Creek: 'America/Dawson_Creek',
  TimeZone.America_Denver: 'America/Denver',
  TimeZone.America_Detroit: 'America/Detroit',
  TimeZone.America_Dominica: 'America/Dominica',
  TimeZone.America_Edmonton: 'America/Edmonton',
  TimeZone.America_Eirunepe: 'America/Eirunepe',
  TimeZone.America_El_Salvador: 'America/El_Salvador',
  TimeZone.America_Ensenada: 'America/Ensenada',
  TimeZone.America_Fort_Nelson: 'America/Fort_Nelson',
  TimeZone.America_Fort_Wayne: 'America/Fort_Wayne',
  TimeZone.America_Fortaleza: 'America/Fortaleza',
  TimeZone.America_Glace_Bay: 'America/Glace_Bay',
  TimeZone.America_Godthab: 'America/Godthab',
  TimeZone.America_Goose_Bay: 'America/Goose_Bay',
  TimeZone.America_Grand_Turk: 'America/Grand_Turk',
  TimeZone.America_Grenada: 'America/Grenada',
  TimeZone.America_Guadeloupe: 'America/Guadeloupe',
  TimeZone.America_Guatemala: 'America/Guatemala',
  TimeZone.America_Guayaquil: 'America/Guayaquil',
  TimeZone.America_Guyana: 'America/Guyana',
  TimeZone.America_Halifax: 'America/Halifax',
  TimeZone.America_Havana: 'America/Havana',
  TimeZone.America_Hermosillo: 'America/Hermosillo',
  TimeZone.America_Indiana_Indianapolis: 'America/Indiana/Indianapolis',
  TimeZone.America_Indiana_Knox: 'America/Indiana/Knox',
  TimeZone.America_Indiana_Marengo: 'America/Indiana/Marengo',
  TimeZone.America_Indiana_Petersburg: 'America/Indiana/Petersburg',
  TimeZone.America_Indiana_Tell_City: 'America/Indiana/Tell_City',
  TimeZone.America_Indiana_Vevay: 'America/Indiana/Vevay',
  TimeZone.America_Indiana_Vincennes: 'America/Indiana/Vincennes',
  TimeZone.America_Indiana_Winamac: 'America/Indiana/Winamac',
  TimeZone.America_Indianapolis: 'America/Indianapolis',
  TimeZone.America_Inuvik: 'America/Inuvik',
  TimeZone.America_Iqaluit: 'America/Iqaluit',
  TimeZone.America_Jamaica: 'America/Jamaica',
  TimeZone.America_Jujuy: 'America/Jujuy',
  TimeZone.America_Juneau: 'America/Juneau',
  TimeZone.America_Kentucky_Louisville: 'America/Kentucky/Louisville',
  TimeZone.America_Kentucky_Monticello: 'America/Kentucky/Monticello',
  TimeZone.America_Knox_IN: 'America/Knox_IN',
  TimeZone.America_Kralendijk: 'America/Kralendijk',
  TimeZone.America_La_Paz: 'America/La_Paz',
  TimeZone.America_Lima: 'America/Lima',
  TimeZone.America_Los_Angeles: 'America/Los_Angeles',
  TimeZone.America_Louisville: 'America/Louisville',
  TimeZone.America_Lower_Princes: 'America/Lower_Princes',
  TimeZone.America_Maceio: 'America/Maceio',
  TimeZone.America_Managua: 'America/Managua',
  TimeZone.America_Manaus: 'America/Manaus',
  TimeZone.America_Marigot: 'America/Marigot',
  TimeZone.America_Martinique: 'America/Martinique',
  TimeZone.America_Matamoros: 'America/Matamoros',
  TimeZone.America_Mazatlan: 'America/Mazatlan',
  TimeZone.America_Mendoza: 'America/Mendoza',
  TimeZone.America_Menominee: 'America/Menominee',
  TimeZone.America_Merida: 'America/Merida',
  TimeZone.America_Metlakatla: 'America/Metlakatla',
  TimeZone.America_Mexico_City: 'America/Mexico_City',
  TimeZone.America_Miquelon: 'America/Miquelon',
  TimeZone.America_Moncton: 'America/Moncton',
  TimeZone.America_Monterrey: 'America/Monterrey',
  TimeZone.America_Montevideo: 'America/Montevideo',
  TimeZone.America_Montreal: 'America/Montreal',
  TimeZone.America_Montserrat: 'America/Montserrat',
  TimeZone.America_Nassau: 'America/Nassau',
  TimeZone.America_New_York: 'America/New_York',
  TimeZone.America_Nipigon: 'America/Nipigon',
  TimeZone.America_Nome: 'America/Nome',
  TimeZone.America_Noronha: 'America/Noronha',
  TimeZone.America_North_Dakota_Beulah: 'America/North_Dakota/Beulah',
  TimeZone.America_North_Dakota_Center: 'America/North_Dakota/Center',
  TimeZone.America_North_Dakota_New_Salem: 'America/North_Dakota/New_Salem',
  TimeZone.America_Ojinaga: 'America/Ojinaga',
  TimeZone.America_Panama: 'America/Panama',
  TimeZone.America_Pangnirtung: 'America/Pangnirtung',
  TimeZone.America_Paramaribo: 'America/Paramaribo',
  TimeZone.America_Phoenix: 'America/Phoenix',
  TimeZone.America_PortMinusauMinusPrince: 'America/Port-au-Prince',
  TimeZone.America_Port_of_Spain: 'America/Port_of_Spain',
  TimeZone.America_Porto_Acre: 'America/Porto_Acre',
  TimeZone.America_Porto_Velho: 'America/Porto_Velho',
  TimeZone.America_Puerto_Rico: 'America/Puerto_Rico',
  TimeZone.America_Rainy_River: 'America/Rainy_River',
  TimeZone.America_Rankin_Inlet: 'America/Rankin_Inlet',
  TimeZone.America_Recife: 'America/Recife',
  TimeZone.America_Regina: 'America/Regina',
  TimeZone.America_Resolute: 'America/Resolute',
  TimeZone.America_Rio_Branco: 'America/Rio_Branco',
  TimeZone.America_Rosario: 'America/Rosario',
  TimeZone.America_Santa_Isabel: 'America/Santa_Isabel',
  TimeZone.America_Santarem: 'America/Santarem',
  TimeZone.America_Santiago: 'America/Santiago',
  TimeZone.America_Santo_Domingo: 'America/Santo_Domingo',
  TimeZone.America_Sao_Paulo: 'America/Sao_Paulo',
  TimeZone.America_Scoresbysund: 'America/Scoresbysund',
  TimeZone.America_Shiprock: 'America/Shiprock',
  TimeZone.America_Sitka: 'America/Sitka',
  TimeZone.America_St_Barthelemy: 'America/St_Barthelemy',
  TimeZone.America_St_Johns: 'America/St_Johns',
  TimeZone.America_St_Kitts: 'America/St_Kitts',
  TimeZone.America_St_Lucia: 'America/St_Lucia',
  TimeZone.America_St_Thomas: 'America/St_Thomas',
  TimeZone.America_St_Vincent: 'America/St_Vincent',
  TimeZone.America_Swift_Current: 'America/Swift_Current',
  TimeZone.America_Tegucigalpa: 'America/Tegucigalpa',
  TimeZone.America_Thule: 'America/Thule',
  TimeZone.America_Thunder_Bay: 'America/Thunder_Bay',
  TimeZone.America_Tijuana: 'America/Tijuana',
  TimeZone.America_Toronto: 'America/Toronto',
  TimeZone.America_Tortola: 'America/Tortola',
  TimeZone.America_Vancouver: 'America/Vancouver',
  TimeZone.America_Virgin: 'America/Virgin',
  TimeZone.America_Whitehorse: 'America/Whitehorse',
  TimeZone.America_Winnipeg: 'America/Winnipeg',
  TimeZone.America_Yakutat: 'America/Yakutat',
  TimeZone.America_Yellowknife: 'America/Yellowknife',
  TimeZone.Antarctica_Casey: 'Antarctica/Casey',
  TimeZone.Antarctica_Davis: 'Antarctica/Davis',
  TimeZone.Antarctica_DumontDUrville: 'Antarctica/DumontDUrville',
  TimeZone.Antarctica_Macquarie: 'Antarctica/Macquarie',
  TimeZone.Antarctica_Mawson: 'Antarctica/Mawson',
  TimeZone.Antarctica_McMurdo: 'Antarctica/McMurdo',
  TimeZone.Antarctica_Palmer: 'Antarctica/Palmer',
  TimeZone.Antarctica_Rothera: 'Antarctica/Rothera',
  TimeZone.Antarctica_South_Pole: 'Antarctica/South_Pole',
  TimeZone.Antarctica_Syowa: 'Antarctica/Syowa',
  TimeZone.Antarctica_Troll: 'Antarctica/Troll',
  TimeZone.Antarctica_Vostok: 'Antarctica/Vostok',
  TimeZone.Arctic_Longyearbyen: 'Arctic/Longyearbyen',
  TimeZone.Asia_Aden: 'Asia/Aden',
  TimeZone.Asia_Almaty: 'Asia/Almaty',
  TimeZone.Asia_Amman: 'Asia/Amman',
  TimeZone.Asia_Anadyr: 'Asia/Anadyr',
  TimeZone.Asia_Aqtau: 'Asia/Aqtau',
  TimeZone.Asia_Aqtobe: 'Asia/Aqtobe',
  TimeZone.Asia_Ashgabat: 'Asia/Ashgabat',
  TimeZone.Asia_Ashkhabad: 'Asia/Ashkhabad',
  TimeZone.Asia_Atyrau: 'Asia/Atyrau',
  TimeZone.Asia_Baghdad: 'Asia/Baghdad',
  TimeZone.Asia_Bahrain: 'Asia/Bahrain',
  TimeZone.Asia_Baku: 'Asia/Baku',
  TimeZone.Asia_Bangkok: 'Asia/Bangkok',
  TimeZone.Asia_Barnaul: 'Asia/Barnaul',
  TimeZone.Asia_Beirut: 'Asia/Beirut',
  TimeZone.Asia_Bishkek: 'Asia/Bishkek',
  TimeZone.Asia_Brunei: 'Asia/Brunei',
  TimeZone.Asia_Calcutta: 'Asia/Calcutta',
  TimeZone.Asia_Chita: 'Asia/Chita',
  TimeZone.Asia_Choibalsan: 'Asia/Choibalsan',
  TimeZone.Asia_Chongqing: 'Asia/Chongqing',
  TimeZone.Asia_Chungking: 'Asia/Chungking',
  TimeZone.Asia_Colombo: 'Asia/Colombo',
  TimeZone.Asia_Dacca: 'Asia/Dacca',
  TimeZone.Asia_Damascus: 'Asia/Damascus',
  TimeZone.Asia_Dhaka: 'Asia/Dhaka',
  TimeZone.Asia_Dili: 'Asia/Dili',
  TimeZone.Asia_Dubai: 'Asia/Dubai',
  TimeZone.Asia_Dushanbe: 'Asia/Dushanbe',
  TimeZone.Asia_Famagusta: 'Asia/Famagusta',
  TimeZone.Asia_Gaza: 'Asia/Gaza',
  TimeZone.Asia_Hanoi: 'Asia/Hanoi',
  TimeZone.Asia_Harbin: 'Asia/Harbin',
  TimeZone.Asia_Hebron: 'Asia/Hebron',
  TimeZone.Asia_Ho_Chi_Minh: 'Asia/Ho_Chi_Minh',
  TimeZone.Asia_Hong_Kong: 'Asia/Hong_Kong',
  TimeZone.Asia_Hovd: 'Asia/Hovd',
  TimeZone.Asia_Irkutsk: 'Asia/Irkutsk',
  TimeZone.Asia_Istanbul: 'Asia/Istanbul',
  TimeZone.Asia_Jakarta: 'Asia/Jakarta',
  TimeZone.Asia_Jayapura: 'Asia/Jayapura',
  TimeZone.Asia_Jerusalem: 'Asia/Jerusalem',
  TimeZone.Asia_Kabul: 'Asia/Kabul',
  TimeZone.Asia_Kamchatka: 'Asia/Kamchatka',
  TimeZone.Asia_Karachi: 'Asia/Karachi',
  TimeZone.Asia_Kashgar: 'Asia/Kashgar',
  TimeZone.Asia_Kathmandu: 'Asia/Kathmandu',
  TimeZone.Asia_Katmandu: 'Asia/Katmandu',
  TimeZone.Asia_Khandyga: 'Asia/Khandyga',
  TimeZone.Asia_Kolkata: 'Asia/Kolkata',
  TimeZone.Asia_Krasnoyarsk: 'Asia/Krasnoyarsk',
  TimeZone.Asia_Kuala_Lumpur: 'Asia/Kuala_Lumpur',
  TimeZone.Asia_Kuching: 'Asia/Kuching',
  TimeZone.Asia_Kuwait: 'Asia/Kuwait',
  TimeZone.Asia_Macao: 'Asia/Macao',
  TimeZone.Asia_Macau: 'Asia/Macau',
  TimeZone.Asia_Magadan: 'Asia/Magadan',
  TimeZone.Asia_Makassar: 'Asia/Makassar',
  TimeZone.Asia_Manila: 'Asia/Manila',
  TimeZone.Asia_Muscat: 'Asia/Muscat',
  TimeZone.Asia_Nicosia: 'Asia/Nicosia',
  TimeZone.Asia_Novokuznetsk: 'Asia/Novokuznetsk',
  TimeZone.Asia_Novosibirsk: 'Asia/Novosibirsk',
  TimeZone.Asia_Omsk: 'Asia/Omsk',
  TimeZone.Asia_Oral: 'Asia/Oral',
  TimeZone.Asia_Phnom_Penh: 'Asia/Phnom_Penh',
  TimeZone.Asia_Pontianak: 'Asia/Pontianak',
  TimeZone.Asia_Pyongyang: 'Asia/Pyongyang',
  TimeZone.Asia_Qatar: 'Asia/Qatar',
  TimeZone.Asia_Qyzylorda: 'Asia/Qyzylorda',
  TimeZone.Asia_Rangoon: 'Asia/Rangoon',
  TimeZone.Asia_Riyadh: 'Asia/Riyadh',
  TimeZone.Asia_Saigon: 'Asia/Saigon',
  TimeZone.Asia_Sakhalin: 'Asia/Sakhalin',
  TimeZone.Asia_Samarkand: 'Asia/Samarkand',
  TimeZone.Asia_Seoul: 'Asia/Seoul',
  TimeZone.Asia_Shanghai: 'Asia/Shanghai',
  TimeZone.Asia_Singapore: 'Asia/Singapore',
  TimeZone.Asia_Srednekolymsk: 'Asia/Srednekolymsk',
  TimeZone.Asia_Taipei: 'Asia/Taipei',
  TimeZone.Asia_Tashkent: 'Asia/Tashkent',
  TimeZone.Asia_Tbilisi: 'Asia/Tbilisi',
  TimeZone.Asia_Tehran: 'Asia/Tehran',
  TimeZone.Asia_Tel_Aviv: 'Asia/Tel_Aviv',
  TimeZone.Asia_Thimbu: 'Asia/Thimbu',
  TimeZone.Asia_Thimphu: 'Asia/Thimphu',
  TimeZone.Asia_Tokyo: 'Asia/Tokyo',
  TimeZone.Asia_Tomsk: 'Asia/Tomsk',
  TimeZone.Asia_Ujung_Pandang: 'Asia/Ujung_Pandang',
  TimeZone.Asia_Ulaanbaatar: 'Asia/Ulaanbaatar',
  TimeZone.Asia_Ulan_Bator: 'Asia/Ulan_Bator',
  TimeZone.Asia_Urumqi: 'Asia/Urumqi',
  TimeZone.Asia_UstMinusNera: 'Asia/Ust-Nera',
  TimeZone.Asia_Vientiane: 'Asia/Vientiane',
  TimeZone.Asia_Vladivostok: 'Asia/Vladivostok',
  TimeZone.Asia_Yakutsk: 'Asia/Yakutsk',
  TimeZone.Asia_Yangon: 'Asia/Yangon',
  TimeZone.Asia_Yekaterinburg: 'Asia/Yekaterinburg',
  TimeZone.Asia_Yerevan: 'Asia/Yerevan',
  TimeZone.Atlantic_Azores: 'Atlantic/Azores',
  TimeZone.Atlantic_Bermuda: 'Atlantic/Bermuda',
  TimeZone.Atlantic_Canary: 'Atlantic/Canary',
  TimeZone.Atlantic_Cape_Verde: 'Atlantic/Cape_Verde',
  TimeZone.Atlantic_Faeroe: 'Atlantic/Faeroe',
  TimeZone.Atlantic_Faroe: 'Atlantic/Faroe',
  TimeZone.Atlantic_Jan_Mayen: 'Atlantic/Jan_Mayen',
  TimeZone.Atlantic_Madeira: 'Atlantic/Madeira',
  TimeZone.Atlantic_Reykjavik: 'Atlantic/Reykjavik',
  TimeZone.Atlantic_South_Georgia: 'Atlantic/South_Georgia',
  TimeZone.Atlantic_St_Helena: 'Atlantic/St_Helena',
  TimeZone.Atlantic_Stanley: 'Atlantic/Stanley',
  TimeZone.Australia_ACT: 'Australia/ACT',
  TimeZone.Australia_Adelaide: 'Australia/Adelaide',
  TimeZone.Australia_Brisbane: 'Australia/Brisbane',
  TimeZone.Australia_Broken_Hill: 'Australia/Broken_Hill',
  TimeZone.Australia_Canberra: 'Australia/Canberra',
  TimeZone.Australia_Currie: 'Australia/Currie',
  TimeZone.Australia_Darwin: 'Australia/Darwin',
  TimeZone.Australia_Eucla: 'Australia/Eucla',
  TimeZone.Australia_Hobart: 'Australia/Hobart',
  TimeZone.Australia_LHI: 'Australia/LHI',
  TimeZone.Australia_Lindeman: 'Australia/Lindeman',
  TimeZone.Australia_Lord_Howe: 'Australia/Lord_Howe',
  TimeZone.Australia_Melbourne: 'Australia/Melbourne',
  TimeZone.Australia_NSW: 'Australia/NSW',
  TimeZone.Australia_North: 'Australia/North',
  TimeZone.Australia_Perth: 'Australia/Perth',
  TimeZone.Australia_Queensland: 'Australia/Queensland',
  TimeZone.Australia_South: 'Australia/South',
  TimeZone.Australia_Sydney: 'Australia/Sydney',
  TimeZone.Australia_Tasmania: 'Australia/Tasmania',
  TimeZone.Australia_Victoria: 'Australia/Victoria',
  TimeZone.Australia_West: 'Australia/West',
  TimeZone.Australia_Yancowinna: 'Australia/Yancowinna',
  TimeZone.Brazil_Acre: 'Brazil/Acre',
  TimeZone.Brazil_DeNoronha: 'Brazil/DeNoronha',
  TimeZone.Brazil_East: 'Brazil/East',
  TimeZone.Brazil_West: 'Brazil/West',
  TimeZone.CET: 'CET',
  TimeZone.CST6CDT: 'CST6CDT',
  TimeZone.Canada_Atlantic: 'Canada/Atlantic',
  TimeZone.Canada_Central: 'Canada/Central',
  TimeZone.Canada_EastMinusSaskatchewan: 'Canada/East-Saskatchewan',
  TimeZone.Canada_Eastern: 'Canada/Eastern',
  TimeZone.Canada_Mountain: 'Canada/Mountain',
  TimeZone.Canada_Newfoundland: 'Canada/Newfoundland',
  TimeZone.Canada_Pacific: 'Canada/Pacific',
  TimeZone.Canada_Saskatchewan: 'Canada/Saskatchewan',
  TimeZone.Canada_Yukon: 'Canada/Yukon',
  TimeZone.Chile_Continental: 'Chile/Continental',
  TimeZone.Chile_EasterIsland: 'Chile/EasterIsland',
  TimeZone.Cuba: 'Cuba',
  TimeZone.EET: 'EET',
  TimeZone.EST: 'EST',
  TimeZone.EST5EDT: 'EST5EDT',
  TimeZone.Egypt: 'Egypt',
  TimeZone.Eire: 'Eire',
  TimeZone.Etc_GMT: 'Etc/GMT',
  TimeZone.Etc_GMTPlus0: 'Etc/GMT+0',
  TimeZone.Etc_GMTPlus1: 'Etc/GMT+1',
  TimeZone.Etc_GMTPlus10: 'Etc/GMT+10',
  TimeZone.Etc_GMTPlus11: 'Etc/GMT+11',
  TimeZone.Etc_GMTPlus12: 'Etc/GMT+12',
  TimeZone.Etc_GMTPlus2: 'Etc/GMT+2',
  TimeZone.Etc_GMTPlus3: 'Etc/GMT+3',
  TimeZone.Etc_GMTPlus4: 'Etc/GMT+4',
  TimeZone.Etc_GMTPlus5: 'Etc/GMT+5',
  TimeZone.Etc_GMTPlus6: 'Etc/GMT+6',
  TimeZone.Etc_GMTPlus7: 'Etc/GMT+7',
  TimeZone.Etc_GMTPlus8: 'Etc/GMT+8',
  TimeZone.Etc_GMTPlus9: 'Etc/GMT+9',
  TimeZone.Etc_GMTMinus0: 'Etc/GMT-0',
  TimeZone.Etc_GMTMinus1: 'Etc/GMT-1',
  TimeZone.Etc_GMTMinus10: 'Etc/GMT-10',
  TimeZone.Etc_GMTMinus11: 'Etc/GMT-11',
  TimeZone.Etc_GMTMinus12: 'Etc/GMT-12',
  TimeZone.Etc_GMTMinus13: 'Etc/GMT-13',
  TimeZone.Etc_GMTMinus14: 'Etc/GMT-14',
  TimeZone.Etc_GMTMinus2: 'Etc/GMT-2',
  TimeZone.Etc_GMTMinus3: 'Etc/GMT-3',
  TimeZone.Etc_GMTMinus4: 'Etc/GMT-4',
  TimeZone.Etc_GMTMinus5: 'Etc/GMT-5',
  TimeZone.Etc_GMTMinus6: 'Etc/GMT-6',
  TimeZone.Etc_GMTMinus7: 'Etc/GMT-7',
  TimeZone.Etc_GMTMinus8: 'Etc/GMT-8',
  TimeZone.Etc_GMTMinus9: 'Etc/GMT-9',
  TimeZone.Etc_GMT0: 'Etc/GMT0',
  TimeZone.Etc_Greenwich: 'Etc/Greenwich',
  TimeZone.Etc_UCT: 'Etc/UCT',
  TimeZone.Etc_UTC: 'Etc/UTC',
  TimeZone.Etc_Universal: 'Etc/Universal',
  TimeZone.Etc_Zulu: 'Etc/Zulu',
  TimeZone.Europe_Amsterdam: 'Europe/Amsterdam',
  TimeZone.Europe_Andorra: 'Europe/Andorra',
  TimeZone.Europe_Astrakhan: 'Europe/Astrakhan',
  TimeZone.Europe_Athens: 'Europe/Athens',
  TimeZone.Europe_Belfast: 'Europe/Belfast',
  TimeZone.Europe_Belgrade: 'Europe/Belgrade',
  TimeZone.Europe_Berlin: 'Europe/Berlin',
  TimeZone.Europe_Bratislava: 'Europe/Bratislava',
  TimeZone.Europe_Brussels: 'Europe/Brussels',
  TimeZone.Europe_Bucharest: 'Europe/Bucharest',
  TimeZone.Europe_Budapest: 'Europe/Budapest',
  TimeZone.Europe_Busingen: 'Europe/Busingen',
  TimeZone.Europe_Chisinau: 'Europe/Chisinau',
  TimeZone.Europe_Copenhagen: 'Europe/Copenhagen',
  TimeZone.Europe_Dublin: 'Europe/Dublin',
  TimeZone.Europe_Gibraltar: 'Europe/Gibraltar',
  TimeZone.Europe_Guernsey: 'Europe/Guernsey',
  TimeZone.Europe_Helsinki: 'Europe/Helsinki',
  TimeZone.Europe_Isle_of_Man: 'Europe/Isle_of_Man',
  TimeZone.Europe_Istanbul: 'Europe/Istanbul',
  TimeZone.Europe_Jersey: 'Europe/Jersey',
  TimeZone.Europe_Kaliningrad: 'Europe/Kaliningrad',
  TimeZone.Europe_Kiev: 'Europe/Kiev',
  TimeZone.Europe_Kirov: 'Europe/Kirov',
  TimeZone.Europe_Lisbon: 'Europe/Lisbon',
  TimeZone.Europe_Ljubljana: 'Europe/Ljubljana',
  TimeZone.Europe_London: 'Europe/London',
  TimeZone.Europe_Luxembourg: 'Europe/Luxembourg',
  TimeZone.Europe_Madrid: 'Europe/Madrid',
  TimeZone.Europe_Malta: 'Europe/Malta',
  TimeZone.Europe_Mariehamn: 'Europe/Mariehamn',
  TimeZone.Europe_Minsk: 'Europe/Minsk',
  TimeZone.Europe_Monaco: 'Europe/Monaco',
  TimeZone.Europe_Moscow: 'Europe/Moscow',
  TimeZone.Europe_Nicosia: 'Europe/Nicosia',
  TimeZone.Europe_Oslo: 'Europe/Oslo',
  TimeZone.Europe_Paris: 'Europe/Paris',
  TimeZone.Europe_Podgorica: 'Europe/Podgorica',
  TimeZone.Europe_Prague: 'Europe/Prague',
  TimeZone.Europe_Riga: 'Europe/Riga',
  TimeZone.Europe_Rome: 'Europe/Rome',
  TimeZone.Europe_Samara: 'Europe/Samara',
  TimeZone.Europe_San_Marino: 'Europe/San_Marino',
  TimeZone.Europe_Sarajevo: 'Europe/Sarajevo',
  TimeZone.Europe_Saratov: 'Europe/Saratov',
  TimeZone.Europe_Simferopol: 'Europe/Simferopol',
  TimeZone.Europe_Skopje: 'Europe/Skopje',
  TimeZone.Europe_Sofia: 'Europe/Sofia',
  TimeZone.Europe_Stockholm: 'Europe/Stockholm',
  TimeZone.Europe_Tallinn: 'Europe/Tallinn',
  TimeZone.Europe_Tirane: 'Europe/Tirane',
  TimeZone.Europe_Tiraspol: 'Europe/Tiraspol',
  TimeZone.Europe_Ulyanovsk: 'Europe/Ulyanovsk',
  TimeZone.Europe_Uzhgorod: 'Europe/Uzhgorod',
  TimeZone.Europe_Vaduz: 'Europe/Vaduz',
  TimeZone.Europe_Vatican: 'Europe/Vatican',
  TimeZone.Europe_Vienna: 'Europe/Vienna',
  TimeZone.Europe_Vilnius: 'Europe/Vilnius',
  TimeZone.Europe_Volgograd: 'Europe/Volgograd',
  TimeZone.Europe_Warsaw: 'Europe/Warsaw',
  TimeZone.Europe_Zagreb: 'Europe/Zagreb',
  TimeZone.Europe_Zaporozhye: 'Europe/Zaporozhye',
  TimeZone.Europe_Zurich: 'Europe/Zurich',
  TimeZone.GB: 'GB',
  TimeZone.GBMinusEire: 'GB-Eire',
  TimeZone.GMT: 'GMT',
  TimeZone.GMTPlus0: 'GMT+0',
  TimeZone.GMTMinus0: 'GMT-0',
  TimeZone.GMT0: 'GMT0',
  TimeZone.Greenwich: 'Greenwich',
  TimeZone.HST: 'HST',
  TimeZone.Hongkong: 'Hongkong',
  TimeZone.Iceland: 'Iceland',
  TimeZone.Indian_Antananarivo: 'Indian/Antananarivo',
  TimeZone.Indian_Chagos: 'Indian/Chagos',
  TimeZone.Indian_Christmas: 'Indian/Christmas',
  TimeZone.Indian_Cocos: 'Indian/Cocos',
  TimeZone.Indian_Comoro: 'Indian/Comoro',
  TimeZone.Indian_Kerguelen: 'Indian/Kerguelen',
  TimeZone.Indian_Mahe: 'Indian/Mahe',
  TimeZone.Indian_Maldives: 'Indian/Maldives',
  TimeZone.Indian_Mauritius: 'Indian/Mauritius',
  TimeZone.Indian_Mayotte: 'Indian/Mayotte',
  TimeZone.Indian_Reunion: 'Indian/Reunion',
  TimeZone.Iran: 'Iran',
  TimeZone.Israel: 'Israel',
  TimeZone.Jamaica: 'Jamaica',
  TimeZone.Japan: 'Japan',
  TimeZone.Kwajalein: 'Kwajalein',
  TimeZone.Libya: 'Libya',
  TimeZone.MET: 'MET',
  TimeZone.MST: 'MST',
  TimeZone.MST7MDT: 'MST7MDT',
  TimeZone.Mexico_BajaNorte: 'Mexico/BajaNorte',
  TimeZone.Mexico_BajaSur: 'Mexico/BajaSur',
  TimeZone.Mexico_General: 'Mexico/General',
  TimeZone.NZ: 'NZ',
  TimeZone.NZMinusCHAT: 'NZ-CHAT',
  TimeZone.Navajo: 'Navajo',
  TimeZone.PRC: 'PRC',
  TimeZone.PST8PDT: 'PST8PDT',
  TimeZone.Pacific_Apia: 'Pacific/Apia',
  TimeZone.Pacific_Auckland: 'Pacific/Auckland',
  TimeZone.Pacific_Bougainville: 'Pacific/Bougainville',
  TimeZone.Pacific_Chatham: 'Pacific/Chatham',
  TimeZone.Pacific_Chuuk: 'Pacific/Chuuk',
  TimeZone.Pacific_Easter: 'Pacific/Easter',
  TimeZone.Pacific_Efate: 'Pacific/Efate',
  TimeZone.Pacific_Enderbury: 'Pacific/Enderbury',
  TimeZone.Pacific_Fakaofo: 'Pacific/Fakaofo',
  TimeZone.Pacific_Fiji: 'Pacific/Fiji',
  TimeZone.Pacific_Funafuti: 'Pacific/Funafuti',
  TimeZone.Pacific_Galapagos: 'Pacific/Galapagos',
  TimeZone.Pacific_Gambier: 'Pacific/Gambier',
  TimeZone.Pacific_Guadalcanal: 'Pacific/Guadalcanal',
  TimeZone.Pacific_Guam: 'Pacific/Guam',
  TimeZone.Pacific_Honolulu: 'Pacific/Honolulu',
  TimeZone.Pacific_Johnston: 'Pacific/Johnston',
  TimeZone.Pacific_Kiritimati: 'Pacific/Kiritimati',
  TimeZone.Pacific_Kosrae: 'Pacific/Kosrae',
  TimeZone.Pacific_Kwajalein: 'Pacific/Kwajalein',
  TimeZone.Pacific_Majuro: 'Pacific/Majuro',
  TimeZone.Pacific_Marquesas: 'Pacific/Marquesas',
  TimeZone.Pacific_Midway: 'Pacific/Midway',
  TimeZone.Pacific_Nauru: 'Pacific/Nauru',
  TimeZone.Pacific_Niue: 'Pacific/Niue',
  TimeZone.Pacific_Norfolk: 'Pacific/Norfolk',
  TimeZone.Pacific_Noumea: 'Pacific/Noumea',
  TimeZone.Pacific_Pago_Pago: 'Pacific/Pago_Pago',
  TimeZone.Pacific_Palau: 'Pacific/Palau',
  TimeZone.Pacific_Pitcairn: 'Pacific/Pitcairn',
  TimeZone.Pacific_Pohnpei: 'Pacific/Pohnpei',
  TimeZone.Pacific_Ponape: 'Pacific/Ponape',
  TimeZone.Pacific_Port_Moresby: 'Pacific/Port_Moresby',
  TimeZone.Pacific_Rarotonga: 'Pacific/Rarotonga',
  TimeZone.Pacific_Saipan: 'Pacific/Saipan',
  TimeZone.Pacific_Samoa: 'Pacific/Samoa',
  TimeZone.Pacific_Tahiti: 'Pacific/Tahiti',
  TimeZone.Pacific_Tarawa: 'Pacific/Tarawa',
  TimeZone.Pacific_Tongatapu: 'Pacific/Tongatapu',
  TimeZone.Pacific_Truk: 'Pacific/Truk',
  TimeZone.Pacific_Wake: 'Pacific/Wake',
  TimeZone.Pacific_Wallis: 'Pacific/Wallis',
  TimeZone.Pacific_Yap: 'Pacific/Yap',
  TimeZone.Poland: 'Poland',
  TimeZone.Portugal: 'Portugal',
  TimeZone.ROC: 'ROC',
  TimeZone.ROK: 'ROK',
  TimeZone.Singapore: 'Singapore',
  TimeZone.Turkey: 'Turkey',
  TimeZone.UCT: 'UCT',
  TimeZone.US_Alaska: 'US/Alaska',
  TimeZone.US_Aleutian: 'US/Aleutian',
  TimeZone.US_Arizona: 'US/Arizona',
  TimeZone.US_Central: 'US/Central',
  TimeZone.US_EastMinusIndiana: 'US/East-Indiana',
  TimeZone.US_Eastern: 'US/Eastern',
  TimeZone.US_Hawaii: 'US/Hawaii',
  TimeZone.US_IndianaMinusStarke: 'US/Indiana-Starke',
  TimeZone.US_Michigan: 'US/Michigan',
  TimeZone.US_Mountain: 'US/Mountain',
  TimeZone.US_Pacific: 'US/Pacific',
  TimeZone.US_Samoa: 'US/Samoa',
  TimeZone.UTC: 'UTC',
  TimeZone.Universal: 'Universal',
  TimeZone.WMinusSU: 'W-SU',
  TimeZone.WET: 'WET',
  TimeZone.Zulu: 'Zulu',
};

const _$DisplayDataModeEnumMap = {
  DisplayDataMode.power: 'power',
  DisplayDataMode.velocity: 'velocity',
};

const _$DisplayFocusModeEnumMap = {
  DisplayFocusMode.mean: 'mean',
  DisplayFocusMode.peak: 'peak',
};
