// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'facility_display_configuration_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FacilityDisplayConfigurationData _$FacilityDisplayConfigurationDataFromJson(
        Map<String, dynamic> json) =>
    $checkedCreate(
      'FacilityDisplayConfigurationData',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const [
            'facilityId',
            'unit',
            'timeZone',
            'qrCodeEnabled',
            'operatingScheduleEnabled',
            'operatingSchedule',
            'shouldForceExercise',
            'signoutDelay',
            'showReviewScreen',
            'defaultBrightness',
            'machinesEnabled',
            'isTorqueEnabled',
            'dataMode',
            'focusMode'
          ],
        );
        final val = FacilityDisplayConfigurationData(
          facilityId: $checkedConvert('facilityId', (v) => v as num),
          unit: $checkedConvert(
              'unit', (v) => $enumDecode(_$DisplayUnitEnumMap, v)),
          timeZone: $checkedConvert(
              'timeZone', (v) => $enumDecode(_$TimeZoneEnumMap, v)),
          qrCodeEnabled: $checkedConvert('qrCodeEnabled', (v) => v as bool),
          operatingScheduleEnabled:
              $checkedConvert('operatingScheduleEnabled', (v) => v as bool),
          operatingSchedule: $checkedConvert(
              'operatingSchedule',
              (v) => FacilityDisplayOperatingSchedule.fromJson(
                  v as Map<String, dynamic>)),
          shouldForceExercise:
              $checkedConvert('shouldForceExercise', (v) => v as bool),
          signoutDelay: $checkedConvert('signoutDelay', (v) => v as num),
          showReviewScreen:
              $checkedConvert('showReviewScreen', (v) => v as bool),
          defaultBrightness:
              $checkedConvert('defaultBrightness', (v) => v as num),
          machinesEnabled: $checkedConvert('machinesEnabled', (v) => v as bool),
          isTorqueEnabled: $checkedConvert('isTorqueEnabled', (v) => v as bool),
          dataMode: $checkedConvert(
              'dataMode', (v) => $enumDecode(_$DisplayDataModeEnumMap, v)),
          focusMode: $checkedConvert(
              'focusMode', (v) => $enumDecode(_$DisplayFocusModeEnumMap, v)),
          performanceDropOff:
              $checkedConvert('performanceDropOff', (v) => v as num?),
          addedMass: $checkedConvert('addedMass', (v) => v as num?),
          secondsDelay: $checkedConvert('secondsDelay', (v) => v as num?),
        );
        return val;
      },
    );

Map<String, dynamic> _$FacilityDisplayConfigurationDataToJson(
    FacilityDisplayConfigurationData instance) {
  final val = <String, dynamic>{
    'facilityId': instance.facilityId,
    'unit': _$DisplayUnitEnumMap[instance.unit]!,
    'timeZone': _$TimeZoneEnumMap[instance.timeZone]!,
    'qrCodeEnabled': instance.qrCodeEnabled,
    'operatingScheduleEnabled': instance.operatingScheduleEnabled,
    'operatingSchedule': instance.operatingSchedule.toJson(),
    'shouldForceExercise': instance.shouldForceExercise,
    'signoutDelay': instance.signoutDelay,
    'showReviewScreen': instance.showReviewScreen,
    'defaultBrightness': instance.defaultBrightness,
    'machinesEnabled': instance.machinesEnabled,
    'isTorqueEnabled': instance.isTorqueEnabled,
    'dataMode': _$DisplayDataModeEnumMap[instance.dataMode]!,
    'focusMode': _$DisplayFocusModeEnumMap[instance.focusMode]!,
  };

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('performanceDropOff', instance.performanceDropOff);
  writeNotNull('addedMass', instance.addedMass);
  writeNotNull('secondsDelay', instance.secondsDelay);
  return val;
}

const _$DisplayUnitEnumMap = {
  DisplayUnit.metric: 'metric',
  DisplayUnit.imperial: 'imperial',
  DisplayUnit.si: 'si',
};

const _$TimeZoneEnumMap = {
  TimeZone.africaSlashAbidjan: 'Africa/Abidjan',
  TimeZone.africaSlashAccra: 'Africa/Accra',
  TimeZone.africaSlashAddisAbaba: 'Africa/Addis_Ababa',
  TimeZone.africaSlashAlgiers: 'Africa/Algiers',
  TimeZone.africaSlashAsmara: 'Africa/Asmara',
  TimeZone.africaSlashAsmera: 'Africa/Asmera',
  TimeZone.africaSlashBamako: 'Africa/Bamako',
  TimeZone.africaSlashBangui: 'Africa/Bangui',
  TimeZone.africaSlashBanjul: 'Africa/Banjul',
  TimeZone.africaSlashBissau: 'Africa/Bissau',
  TimeZone.africaSlashBlantyre: 'Africa/Blantyre',
  TimeZone.africaSlashBrazzaville: 'Africa/Brazzaville',
  TimeZone.africaSlashBujumbura: 'Africa/Bujumbura',
  TimeZone.africaSlashCairo: 'Africa/Cairo',
  TimeZone.africaSlashCasablanca: 'Africa/Casablanca',
  TimeZone.africaSlashCeuta: 'Africa/Ceuta',
  TimeZone.africaSlashConakry: 'Africa/Conakry',
  TimeZone.africaSlashDakar: 'Africa/Dakar',
  TimeZone.africaSlashDarEsSalaam: 'Africa/Dar_es_Salaam',
  TimeZone.africaSlashDjibouti: 'Africa/Djibouti',
  TimeZone.africaSlashDouala: 'Africa/Douala',
  TimeZone.africaSlashElAaiun: 'Africa/El_Aaiun',
  TimeZone.africaSlashFreetown: 'Africa/Freetown',
  TimeZone.africaSlashGaborone: 'Africa/Gaborone',
  TimeZone.africaSlashHarare: 'Africa/Harare',
  TimeZone.africaSlashJohannesburg: 'Africa/Johannesburg',
  TimeZone.africaSlashJuba: 'Africa/Juba',
  TimeZone.africaSlashKampala: 'Africa/Kampala',
  TimeZone.africaSlashKhartoum: 'Africa/Khartoum',
  TimeZone.africaSlashKigali: 'Africa/Kigali',
  TimeZone.africaSlashKinshasa: 'Africa/Kinshasa',
  TimeZone.africaSlashLagos: 'Africa/Lagos',
  TimeZone.africaSlashLibreville: 'Africa/Libreville',
  TimeZone.africaSlashLome: 'Africa/Lome',
  TimeZone.africaSlashLuanda: 'Africa/Luanda',
  TimeZone.africaSlashLubumbashi: 'Africa/Lubumbashi',
  TimeZone.africaSlashLusaka: 'Africa/Lusaka',
  TimeZone.africaSlashMalabo: 'Africa/Malabo',
  TimeZone.africaSlashMaputo: 'Africa/Maputo',
  TimeZone.africaSlashMaseru: 'Africa/Maseru',
  TimeZone.africaSlashMbabane: 'Africa/Mbabane',
  TimeZone.africaSlashMogadishu: 'Africa/Mogadishu',
  TimeZone.africaSlashMonrovia: 'Africa/Monrovia',
  TimeZone.africaSlashNairobi: 'Africa/Nairobi',
  TimeZone.africaSlashNdjamena: 'Africa/Ndjamena',
  TimeZone.africaSlashNiamey: 'Africa/Niamey',
  TimeZone.africaSlashNouakchott: 'Africa/Nouakchott',
  TimeZone.africaSlashOuagadougou: 'Africa/Ouagadougou',
  TimeZone.africaSlashPortoNovo: 'Africa/Porto-Novo',
  TimeZone.africaSlashSaoTome: 'Africa/Sao_Tome',
  TimeZone.africaSlashTimbuktu: 'Africa/Timbuktu',
  TimeZone.africaSlashTripoli: 'Africa/Tripoli',
  TimeZone.africaSlashTunis: 'Africa/Tunis',
  TimeZone.africaSlashWindhoek: 'Africa/Windhoek',
  TimeZone.americaSlashAdak: 'America/Adak',
  TimeZone.americaSlashAnchorage: 'America/Anchorage',
  TimeZone.americaSlashAnguilla: 'America/Anguilla',
  TimeZone.americaSlashAntigua: 'America/Antigua',
  TimeZone.americaSlashAraguaina: 'America/Araguaina',
  TimeZone.americaSlashArgentinaSlashBuenosAires:
      'America/Argentina/Buenos_Aires',
  TimeZone.americaSlashArgentinaSlashCatamarca: 'America/Argentina/Catamarca',
  TimeZone.americaSlashArgentinaSlashComodRivadavia:
      'America/Argentina/ComodRivadavia',
  TimeZone.americaSlashArgentinaSlashCordoba: 'America/Argentina/Cordoba',
  TimeZone.americaSlashArgentinaSlashJujuy: 'America/Argentina/Jujuy',
  TimeZone.americaSlashArgentinaSlashLaRioja: 'America/Argentina/La_Rioja',
  TimeZone.americaSlashArgentinaSlashMendoza: 'America/Argentina/Mendoza',
  TimeZone.americaSlashArgentinaSlashRioGallegos:
      'America/Argentina/Rio_Gallegos',
  TimeZone.americaSlashArgentinaSlashSalta: 'America/Argentina/Salta',
  TimeZone.americaSlashArgentinaSlashSanJuan: 'America/Argentina/San_Juan',
  TimeZone.americaSlashArgentinaSlashSanLuis: 'America/Argentina/San_Luis',
  TimeZone.americaSlashArgentinaSlashTucuman: 'America/Argentina/Tucuman',
  TimeZone.americaSlashArgentinaSlashUshuaia: 'America/Argentina/Ushuaia',
  TimeZone.americaSlashAruba: 'America/Aruba',
  TimeZone.americaSlashAsuncion: 'America/Asuncion',
  TimeZone.americaSlashAtikokan: 'America/Atikokan',
  TimeZone.americaSlashAtka: 'America/Atka',
  TimeZone.americaSlashBahia: 'America/Bahia',
  TimeZone.americaSlashBahiaBanderas: 'America/Bahia_Banderas',
  TimeZone.americaSlashBarbados: 'America/Barbados',
  TimeZone.americaSlashBelem: 'America/Belem',
  TimeZone.americaSlashBelize: 'America/Belize',
  TimeZone.americaSlashBlancSablon: 'America/Blanc-Sablon',
  TimeZone.americaSlashBoaVista: 'America/Boa_Vista',
  TimeZone.americaSlashBogota: 'America/Bogota',
  TimeZone.americaSlashBoise: 'America/Boise',
  TimeZone.americaSlashBuenosAires: 'America/Buenos_Aires',
  TimeZone.americaSlashCambridgeBay: 'America/Cambridge_Bay',
  TimeZone.americaSlashCampoGrande: 'America/Campo_Grande',
  TimeZone.americaSlashCancun: 'America/Cancun',
  TimeZone.americaSlashCaracas: 'America/Caracas',
  TimeZone.americaSlashCatamarca: 'America/Catamarca',
  TimeZone.americaSlashCayenne: 'America/Cayenne',
  TimeZone.americaSlashCayman: 'America/Cayman',
  TimeZone.americaSlashChicago: 'America/Chicago',
  TimeZone.americaSlashChihuahua: 'America/Chihuahua',
  TimeZone.americaSlashCoralHarbour: 'America/Coral_Harbour',
  TimeZone.americaSlashCordoba: 'America/Cordoba',
  TimeZone.americaSlashCostaRica: 'America/Costa_Rica',
  TimeZone.americaSlashCreston: 'America/Creston',
  TimeZone.americaSlashCuiaba: 'America/Cuiaba',
  TimeZone.americaSlashCuracao: 'America/Curacao',
  TimeZone.americaSlashDanmarkshavn: 'America/Danmarkshavn',
  TimeZone.americaSlashDawson: 'America/Dawson',
  TimeZone.americaSlashDawsonCreek: 'America/Dawson_Creek',
  TimeZone.americaSlashDenver: 'America/Denver',
  TimeZone.americaSlashDetroit: 'America/Detroit',
  TimeZone.americaSlashDominica: 'America/Dominica',
  TimeZone.americaSlashEdmonton: 'America/Edmonton',
  TimeZone.americaSlashEirunepe: 'America/Eirunepe',
  TimeZone.americaSlashElSalvador: 'America/El_Salvador',
  TimeZone.americaSlashEnsenada: 'America/Ensenada',
  TimeZone.americaSlashFortNelson: 'America/Fort_Nelson',
  TimeZone.americaSlashFortWayne: 'America/Fort_Wayne',
  TimeZone.americaSlashFortaleza: 'America/Fortaleza',
  TimeZone.americaSlashGlaceBay: 'America/Glace_Bay',
  TimeZone.americaSlashGodthab: 'America/Godthab',
  TimeZone.americaSlashGooseBay: 'America/Goose_Bay',
  TimeZone.americaSlashGrandTurk: 'America/Grand_Turk',
  TimeZone.americaSlashGrenada: 'America/Grenada',
  TimeZone.americaSlashGuadeloupe: 'America/Guadeloupe',
  TimeZone.americaSlashGuatemala: 'America/Guatemala',
  TimeZone.americaSlashGuayaquil: 'America/Guayaquil',
  TimeZone.americaSlashGuyana: 'America/Guyana',
  TimeZone.americaSlashHalifax: 'America/Halifax',
  TimeZone.americaSlashHavana: 'America/Havana',
  TimeZone.americaSlashHermosillo: 'America/Hermosillo',
  TimeZone.americaSlashIndianaSlashIndianapolis: 'America/Indiana/Indianapolis',
  TimeZone.americaSlashIndianaSlashKnox: 'America/Indiana/Knox',
  TimeZone.americaSlashIndianaSlashMarengo: 'America/Indiana/Marengo',
  TimeZone.americaSlashIndianaSlashPetersburg: 'America/Indiana/Petersburg',
  TimeZone.americaSlashIndianaSlashTellCity: 'America/Indiana/Tell_City',
  TimeZone.americaSlashIndianaSlashVevay: 'America/Indiana/Vevay',
  TimeZone.americaSlashIndianaSlashVincennes: 'America/Indiana/Vincennes',
  TimeZone.americaSlashIndianaSlashWinamac: 'America/Indiana/Winamac',
  TimeZone.americaSlashIndianapolis: 'America/Indianapolis',
  TimeZone.americaSlashInuvik: 'America/Inuvik',
  TimeZone.americaSlashIqaluit: 'America/Iqaluit',
  TimeZone.americaSlashJamaica: 'America/Jamaica',
  TimeZone.americaSlashJujuy: 'America/Jujuy',
  TimeZone.americaSlashJuneau: 'America/Juneau',
  TimeZone.americaSlashKentuckySlashLouisville: 'America/Kentucky/Louisville',
  TimeZone.americaSlashKentuckySlashMonticello: 'America/Kentucky/Monticello',
  TimeZone.americaSlashKnoxIN: 'America/Knox_IN',
  TimeZone.americaSlashKralendijk: 'America/Kralendijk',
  TimeZone.americaSlashLaPaz: 'America/La_Paz',
  TimeZone.americaSlashLima: 'America/Lima',
  TimeZone.americaSlashLosAngeles: 'America/Los_Angeles',
  TimeZone.americaSlashLouisville: 'America/Louisville',
  TimeZone.americaSlashLowerPrinces: 'America/Lower_Princes',
  TimeZone.americaSlashMaceio: 'America/Maceio',
  TimeZone.americaSlashManagua: 'America/Managua',
  TimeZone.americaSlashManaus: 'America/Manaus',
  TimeZone.americaSlashMarigot: 'America/Marigot',
  TimeZone.americaSlashMartinique: 'America/Martinique',
  TimeZone.americaSlashMatamoros: 'America/Matamoros',
  TimeZone.americaSlashMazatlan: 'America/Mazatlan',
  TimeZone.americaSlashMendoza: 'America/Mendoza',
  TimeZone.americaSlashMenominee: 'America/Menominee',
  TimeZone.americaSlashMerida: 'America/Merida',
  TimeZone.americaSlashMetlakatla: 'America/Metlakatla',
  TimeZone.americaSlashMexicoCity: 'America/Mexico_City',
  TimeZone.americaSlashMiquelon: 'America/Miquelon',
  TimeZone.americaSlashMoncton: 'America/Moncton',
  TimeZone.americaSlashMonterrey: 'America/Monterrey',
  TimeZone.americaSlashMontevideo: 'America/Montevideo',
  TimeZone.americaSlashMontreal: 'America/Montreal',
  TimeZone.americaSlashMontserrat: 'America/Montserrat',
  TimeZone.americaSlashNassau: 'America/Nassau',
  TimeZone.americaSlashNewYork: 'America/New_York',
  TimeZone.americaSlashNipigon: 'America/Nipigon',
  TimeZone.americaSlashNome: 'America/Nome',
  TimeZone.americaSlashNoronha: 'America/Noronha',
  TimeZone.americaSlashNorthDakotaSlashBeulah: 'America/North_Dakota/Beulah',
  TimeZone.americaSlashNorthDakotaSlashCenter: 'America/North_Dakota/Center',
  TimeZone.americaSlashNorthDakotaSlashNewSalem:
      'America/North_Dakota/New_Salem',
  TimeZone.americaSlashOjinaga: 'America/Ojinaga',
  TimeZone.americaSlashPanama: 'America/Panama',
  TimeZone.americaSlashPangnirtung: 'America/Pangnirtung',
  TimeZone.americaSlashParamaribo: 'America/Paramaribo',
  TimeZone.americaSlashPhoenix: 'America/Phoenix',
  TimeZone.americaSlashPortAuPrince: 'America/Port-au-Prince',
  TimeZone.americaSlashPortOfSpain: 'America/Port_of_Spain',
  TimeZone.americaSlashPortoAcre: 'America/Porto_Acre',
  TimeZone.americaSlashPortoVelho: 'America/Porto_Velho',
  TimeZone.americaSlashPuertoRico: 'America/Puerto_Rico',
  TimeZone.americaSlashRainyRiver: 'America/Rainy_River',
  TimeZone.americaSlashRankinInlet: 'America/Rankin_Inlet',
  TimeZone.americaSlashRecife: 'America/Recife',
  TimeZone.americaSlashRegina: 'America/Regina',
  TimeZone.americaSlashResolute: 'America/Resolute',
  TimeZone.americaSlashRioBranco: 'America/Rio_Branco',
  TimeZone.americaSlashRosario: 'America/Rosario',
  TimeZone.americaSlashSantaIsabel: 'America/Santa_Isabel',
  TimeZone.americaSlashSantarem: 'America/Santarem',
  TimeZone.americaSlashSantiago: 'America/Santiago',
  TimeZone.americaSlashSantoDomingo: 'America/Santo_Domingo',
  TimeZone.americaSlashSaoPaulo: 'America/Sao_Paulo',
  TimeZone.americaSlashScoresbysund: 'America/Scoresbysund',
  TimeZone.americaSlashShiprock: 'America/Shiprock',
  TimeZone.americaSlashSitka: 'America/Sitka',
  TimeZone.americaSlashStBarthelemy: 'America/St_Barthelemy',
  TimeZone.americaSlashStJohns: 'America/St_Johns',
  TimeZone.americaSlashStKitts: 'America/St_Kitts',
  TimeZone.americaSlashStLucia: 'America/St_Lucia',
  TimeZone.americaSlashStThomas: 'America/St_Thomas',
  TimeZone.americaSlashStVincent: 'America/St_Vincent',
  TimeZone.americaSlashSwiftCurrent: 'America/Swift_Current',
  TimeZone.americaSlashTegucigalpa: 'America/Tegucigalpa',
  TimeZone.americaSlashThule: 'America/Thule',
  TimeZone.americaSlashThunderBay: 'America/Thunder_Bay',
  TimeZone.americaSlashTijuana: 'America/Tijuana',
  TimeZone.americaSlashToronto: 'America/Toronto',
  TimeZone.americaSlashTortola: 'America/Tortola',
  TimeZone.americaSlashVancouver: 'America/Vancouver',
  TimeZone.americaSlashVirgin: 'America/Virgin',
  TimeZone.americaSlashWhitehorse: 'America/Whitehorse',
  TimeZone.americaSlashWinnipeg: 'America/Winnipeg',
  TimeZone.americaSlashYakutat: 'America/Yakutat',
  TimeZone.americaSlashYellowknife: 'America/Yellowknife',
  TimeZone.antarcticaSlashCasey: 'Antarctica/Casey',
  TimeZone.antarcticaSlashDavis: 'Antarctica/Davis',
  TimeZone.antarcticaSlashDumontDUrville: 'Antarctica/DumontDUrville',
  TimeZone.antarcticaSlashMacquarie: 'Antarctica/Macquarie',
  TimeZone.antarcticaSlashMawson: 'Antarctica/Mawson',
  TimeZone.antarcticaSlashMcMurdo: 'Antarctica/McMurdo',
  TimeZone.antarcticaSlashPalmer: 'Antarctica/Palmer',
  TimeZone.antarcticaSlashRothera: 'Antarctica/Rothera',
  TimeZone.antarcticaSlashSouthPole: 'Antarctica/South_Pole',
  TimeZone.antarcticaSlashSyowa: 'Antarctica/Syowa',
  TimeZone.antarcticaSlashTroll: 'Antarctica/Troll',
  TimeZone.antarcticaSlashVostok: 'Antarctica/Vostok',
  TimeZone.arcticSlashLongyearbyen: 'Arctic/Longyearbyen',
  TimeZone.asiaSlashAden: 'Asia/Aden',
  TimeZone.asiaSlashAlmaty: 'Asia/Almaty',
  TimeZone.asiaSlashAmman: 'Asia/Amman',
  TimeZone.asiaSlashAnadyr: 'Asia/Anadyr',
  TimeZone.asiaSlashAqtau: 'Asia/Aqtau',
  TimeZone.asiaSlashAqtobe: 'Asia/Aqtobe',
  TimeZone.asiaSlashAshgabat: 'Asia/Ashgabat',
  TimeZone.asiaSlashAshkhabad: 'Asia/Ashkhabad',
  TimeZone.asiaSlashAtyrau: 'Asia/Atyrau',
  TimeZone.asiaSlashBaghdad: 'Asia/Baghdad',
  TimeZone.asiaSlashBahrain: 'Asia/Bahrain',
  TimeZone.asiaSlashBaku: 'Asia/Baku',
  TimeZone.asiaSlashBangkok: 'Asia/Bangkok',
  TimeZone.asiaSlashBarnaul: 'Asia/Barnaul',
  TimeZone.asiaSlashBeirut: 'Asia/Beirut',
  TimeZone.asiaSlashBishkek: 'Asia/Bishkek',
  TimeZone.asiaSlashBrunei: 'Asia/Brunei',
  TimeZone.asiaSlashCalcutta: 'Asia/Calcutta',
  TimeZone.asiaSlashChita: 'Asia/Chita',
  TimeZone.asiaSlashChoibalsan: 'Asia/Choibalsan',
  TimeZone.asiaSlashChongqing: 'Asia/Chongqing',
  TimeZone.asiaSlashChungking: 'Asia/Chungking',
  TimeZone.asiaSlashColombo: 'Asia/Colombo',
  TimeZone.asiaSlashDacca: 'Asia/Dacca',
  TimeZone.asiaSlashDamascus: 'Asia/Damascus',
  TimeZone.asiaSlashDhaka: 'Asia/Dhaka',
  TimeZone.asiaSlashDili: 'Asia/Dili',
  TimeZone.asiaSlashDubai: 'Asia/Dubai',
  TimeZone.asiaSlashDushanbe: 'Asia/Dushanbe',
  TimeZone.asiaSlashFamagusta: 'Asia/Famagusta',
  TimeZone.asiaSlashGaza: 'Asia/Gaza',
  TimeZone.asiaSlashHanoi: 'Asia/Hanoi',
  TimeZone.asiaSlashHarbin: 'Asia/Harbin',
  TimeZone.asiaSlashHebron: 'Asia/Hebron',
  TimeZone.asiaSlashHoChiMinh: 'Asia/Ho_Chi_Minh',
  TimeZone.asiaSlashHongKong: 'Asia/Hong_Kong',
  TimeZone.asiaSlashHovd: 'Asia/Hovd',
  TimeZone.asiaSlashIrkutsk: 'Asia/Irkutsk',
  TimeZone.asiaSlashIstanbul: 'Asia/Istanbul',
  TimeZone.asiaSlashJakarta: 'Asia/Jakarta',
  TimeZone.asiaSlashJayapura: 'Asia/Jayapura',
  TimeZone.asiaSlashJerusalem: 'Asia/Jerusalem',
  TimeZone.asiaSlashKabul: 'Asia/Kabul',
  TimeZone.asiaSlashKamchatka: 'Asia/Kamchatka',
  TimeZone.asiaSlashKarachi: 'Asia/Karachi',
  TimeZone.asiaSlashKashgar: 'Asia/Kashgar',
  TimeZone.asiaSlashKathmandu: 'Asia/Kathmandu',
  TimeZone.asiaSlashKatmandu: 'Asia/Katmandu',
  TimeZone.asiaSlashKhandyga: 'Asia/Khandyga',
  TimeZone.asiaSlashKolkata: 'Asia/Kolkata',
  TimeZone.asiaSlashKrasnoyarsk: 'Asia/Krasnoyarsk',
  TimeZone.asiaSlashKualaLumpur: 'Asia/Kuala_Lumpur',
  TimeZone.asiaSlashKuching: 'Asia/Kuching',
  TimeZone.asiaSlashKuwait: 'Asia/Kuwait',
  TimeZone.asiaSlashMacao: 'Asia/Macao',
  TimeZone.asiaSlashMacau: 'Asia/Macau',
  TimeZone.asiaSlashMagadan: 'Asia/Magadan',
  TimeZone.asiaSlashMakassar: 'Asia/Makassar',
  TimeZone.asiaSlashManila: 'Asia/Manila',
  TimeZone.asiaSlashMuscat: 'Asia/Muscat',
  TimeZone.asiaSlashNicosia: 'Asia/Nicosia',
  TimeZone.asiaSlashNovokuznetsk: 'Asia/Novokuznetsk',
  TimeZone.asiaSlashNovosibirsk: 'Asia/Novosibirsk',
  TimeZone.asiaSlashOmsk: 'Asia/Omsk',
  TimeZone.asiaSlashOral: 'Asia/Oral',
  TimeZone.asiaSlashPhnomPenh: 'Asia/Phnom_Penh',
  TimeZone.asiaSlashPontianak: 'Asia/Pontianak',
  TimeZone.asiaSlashPyongyang: 'Asia/Pyongyang',
  TimeZone.asiaSlashQatar: 'Asia/Qatar',
  TimeZone.asiaSlashQyzylorda: 'Asia/Qyzylorda',
  TimeZone.asiaSlashRangoon: 'Asia/Rangoon',
  TimeZone.asiaSlashRiyadh: 'Asia/Riyadh',
  TimeZone.asiaSlashSaigon: 'Asia/Saigon',
  TimeZone.asiaSlashSakhalin: 'Asia/Sakhalin',
  TimeZone.asiaSlashSamarkand: 'Asia/Samarkand',
  TimeZone.asiaSlashSeoul: 'Asia/Seoul',
  TimeZone.asiaSlashShanghai: 'Asia/Shanghai',
  TimeZone.asiaSlashSingapore: 'Asia/Singapore',
  TimeZone.asiaSlashSrednekolymsk: 'Asia/Srednekolymsk',
  TimeZone.asiaSlashTaipei: 'Asia/Taipei',
  TimeZone.asiaSlashTashkent: 'Asia/Tashkent',
  TimeZone.asiaSlashTbilisi: 'Asia/Tbilisi',
  TimeZone.asiaSlashTehran: 'Asia/Tehran',
  TimeZone.asiaSlashTelAviv: 'Asia/Tel_Aviv',
  TimeZone.asiaSlashThimbu: 'Asia/Thimbu',
  TimeZone.asiaSlashThimphu: 'Asia/Thimphu',
  TimeZone.asiaSlashTokyo: 'Asia/Tokyo',
  TimeZone.asiaSlashTomsk: 'Asia/Tomsk',
  TimeZone.asiaSlashUjungPandang: 'Asia/Ujung_Pandang',
  TimeZone.asiaSlashUlaanbaatar: 'Asia/Ulaanbaatar',
  TimeZone.asiaSlashUlanBator: 'Asia/Ulan_Bator',
  TimeZone.asiaSlashUrumqi: 'Asia/Urumqi',
  TimeZone.asiaSlashUstNera: 'Asia/Ust-Nera',
  TimeZone.asiaSlashVientiane: 'Asia/Vientiane',
  TimeZone.asiaSlashVladivostok: 'Asia/Vladivostok',
  TimeZone.asiaSlashYakutsk: 'Asia/Yakutsk',
  TimeZone.asiaSlashYangon: 'Asia/Yangon',
  TimeZone.asiaSlashYekaterinburg: 'Asia/Yekaterinburg',
  TimeZone.asiaSlashYerevan: 'Asia/Yerevan',
  TimeZone.atlanticSlashAzores: 'Atlantic/Azores',
  TimeZone.atlanticSlashBermuda: 'Atlantic/Bermuda',
  TimeZone.atlanticSlashCanary: 'Atlantic/Canary',
  TimeZone.atlanticSlashCapeVerde: 'Atlantic/Cape_Verde',
  TimeZone.atlanticSlashFaeroe: 'Atlantic/Faeroe',
  TimeZone.atlanticSlashFaroe: 'Atlantic/Faroe',
  TimeZone.atlanticSlashJanMayen: 'Atlantic/Jan_Mayen',
  TimeZone.atlanticSlashMadeira: 'Atlantic/Madeira',
  TimeZone.atlanticSlashReykjavik: 'Atlantic/Reykjavik',
  TimeZone.atlanticSlashSouthGeorgia: 'Atlantic/South_Georgia',
  TimeZone.atlanticSlashStHelena: 'Atlantic/St_Helena',
  TimeZone.atlanticSlashStanley: 'Atlantic/Stanley',
  TimeZone.australiaSlashACT: 'Australia/ACT',
  TimeZone.australiaSlashAdelaide: 'Australia/Adelaide',
  TimeZone.australiaSlashBrisbane: 'Australia/Brisbane',
  TimeZone.australiaSlashBrokenHill: 'Australia/Broken_Hill',
  TimeZone.australiaSlashCanberra: 'Australia/Canberra',
  TimeZone.australiaSlashCurrie: 'Australia/Currie',
  TimeZone.australiaSlashDarwin: 'Australia/Darwin',
  TimeZone.australiaSlashEucla: 'Australia/Eucla',
  TimeZone.australiaSlashHobart: 'Australia/Hobart',
  TimeZone.australiaSlashLHI: 'Australia/LHI',
  TimeZone.australiaSlashLindeman: 'Australia/Lindeman',
  TimeZone.australiaSlashLordHowe: 'Australia/Lord_Howe',
  TimeZone.australiaSlashMelbourne: 'Australia/Melbourne',
  TimeZone.australiaSlashNSW: 'Australia/NSW',
  TimeZone.australiaSlashNorth: 'Australia/North',
  TimeZone.australiaSlashPerth: 'Australia/Perth',
  TimeZone.australiaSlashQueensland: 'Australia/Queensland',
  TimeZone.australiaSlashSouth: 'Australia/South',
  TimeZone.australiaSlashSydney: 'Australia/Sydney',
  TimeZone.australiaSlashTasmania: 'Australia/Tasmania',
  TimeZone.australiaSlashVictoria: 'Australia/Victoria',
  TimeZone.australiaSlashWest: 'Australia/West',
  TimeZone.australiaSlashYancowinna: 'Australia/Yancowinna',
  TimeZone.brazilSlashAcre: 'Brazil/Acre',
  TimeZone.brazilSlashDeNoronha: 'Brazil/DeNoronha',
  TimeZone.brazilSlashEast: 'Brazil/East',
  TimeZone.brazilSlashWest: 'Brazil/West',
  TimeZone.CET: 'CET',
  TimeZone.cST6CDT: 'CST6CDT',
  TimeZone.canadaSlashAtlantic: 'Canada/Atlantic',
  TimeZone.canadaSlashCentral: 'Canada/Central',
  TimeZone.canadaSlashEastSaskatchewan: 'Canada/East-Saskatchewan',
  TimeZone.canadaSlashEastern: 'Canada/Eastern',
  TimeZone.canadaSlashMountain: 'Canada/Mountain',
  TimeZone.canadaSlashNewfoundland: 'Canada/Newfoundland',
  TimeZone.canadaSlashPacific: 'Canada/Pacific',
  TimeZone.canadaSlashSaskatchewan: 'Canada/Saskatchewan',
  TimeZone.canadaSlashYukon: 'Canada/Yukon',
  TimeZone.chileSlashContinental: 'Chile/Continental',
  TimeZone.chileSlashEasterIsland: 'Chile/EasterIsland',
  TimeZone.cuba: 'Cuba',
  TimeZone.EET: 'EET',
  TimeZone.EST: 'EST',
  TimeZone.eST5EDT: 'EST5EDT',
  TimeZone.egypt: 'Egypt',
  TimeZone.eire: 'Eire',
  TimeZone.etcSlashGMT: 'Etc/GMT',
  TimeZone.etcSlashGMTPlus0: 'Etc/GMT+0',
  TimeZone.etcSlashGMTPlus1: 'Etc/GMT+1',
  TimeZone.etcSlashGMTPlus10: 'Etc/GMT+10',
  TimeZone.etcSlashGMTPlus11: 'Etc/GMT+11',
  TimeZone.etcSlashGMTPlus12: 'Etc/GMT+12',
  TimeZone.etcSlashGMTPlus2: 'Etc/GMT+2',
  TimeZone.etcSlashGMTPlus3: 'Etc/GMT+3',
  TimeZone.etcSlashGMTPlus4: 'Etc/GMT+4',
  TimeZone.etcSlashGMTPlus5: 'Etc/GMT+5',
  TimeZone.etcSlashGMTPlus6: 'Etc/GMT+6',
  TimeZone.etcSlashGMTPlus7: 'Etc/GMT+7',
  TimeZone.etcSlashGMTPlus8: 'Etc/GMT+8',
  TimeZone.etcSlashGMTPlus9: 'Etc/GMT+9',
  TimeZone.etcSlashGMT0: 'Etc/GMT-0',
  TimeZone.etcSlashGMT1: 'Etc/GMT-1',
  TimeZone.etcSlashGMT10: 'Etc/GMT-10',
  TimeZone.etcSlashGMT11: 'Etc/GMT-11',
  TimeZone.etcSlashGMT12: 'Etc/GMT-12',
  TimeZone.etcSlashGMT13: 'Etc/GMT-13',
  TimeZone.etcSlashGMT14: 'Etc/GMT-14',
  TimeZone.etcSlashGMT2: 'Etc/GMT-2',
  TimeZone.etcSlashGMT3: 'Etc/GMT-3',
  TimeZone.etcSlashGMT4: 'Etc/GMT-4',
  TimeZone.etcSlashGMT5: 'Etc/GMT-5',
  TimeZone.etcSlashGMT6: 'Etc/GMT-6',
  TimeZone.etcSlashGMT7: 'Etc/GMT-7',
  TimeZone.etcSlashGMT8: 'Etc/GMT-8',
  TimeZone.etcSlashGMT9: 'Etc/GMT-9',
  TimeZone.etcSlashGMT02: 'Etc/GMT0',
  TimeZone.etcSlashGreenwich: 'Etc/Greenwich',
  TimeZone.etcSlashUCT: 'Etc/UCT',
  TimeZone.etcSlashUTC: 'Etc/UTC',
  TimeZone.etcSlashUniversal: 'Etc/Universal',
  TimeZone.etcSlashZulu: 'Etc/Zulu',
  TimeZone.europeSlashAmsterdam: 'Europe/Amsterdam',
  TimeZone.europeSlashAndorra: 'Europe/Andorra',
  TimeZone.europeSlashAstrakhan: 'Europe/Astrakhan',
  TimeZone.europeSlashAthens: 'Europe/Athens',
  TimeZone.europeSlashBelfast: 'Europe/Belfast',
  TimeZone.europeSlashBelgrade: 'Europe/Belgrade',
  TimeZone.europeSlashBerlin: 'Europe/Berlin',
  TimeZone.europeSlashBratislava: 'Europe/Bratislava',
  TimeZone.europeSlashBrussels: 'Europe/Brussels',
  TimeZone.europeSlashBucharest: 'Europe/Bucharest',
  TimeZone.europeSlashBudapest: 'Europe/Budapest',
  TimeZone.europeSlashBusingen: 'Europe/Busingen',
  TimeZone.europeSlashChisinau: 'Europe/Chisinau',
  TimeZone.europeSlashCopenhagen: 'Europe/Copenhagen',
  TimeZone.europeSlashDublin: 'Europe/Dublin',
  TimeZone.europeSlashGibraltar: 'Europe/Gibraltar',
  TimeZone.europeSlashGuernsey: 'Europe/Guernsey',
  TimeZone.europeSlashHelsinki: 'Europe/Helsinki',
  TimeZone.europeSlashIsleOfMan: 'Europe/Isle_of_Man',
  TimeZone.europeSlashIstanbul: 'Europe/Istanbul',
  TimeZone.europeSlashJersey: 'Europe/Jersey',
  TimeZone.europeSlashKaliningrad: 'Europe/Kaliningrad',
  TimeZone.europeSlashKiev: 'Europe/Kiev',
  TimeZone.europeSlashKirov: 'Europe/Kirov',
  TimeZone.europeSlashLisbon: 'Europe/Lisbon',
  TimeZone.europeSlashLjubljana: 'Europe/Ljubljana',
  TimeZone.europeSlashLondon: 'Europe/London',
  TimeZone.europeSlashLuxembourg: 'Europe/Luxembourg',
  TimeZone.europeSlashMadrid: 'Europe/Madrid',
  TimeZone.europeSlashMalta: 'Europe/Malta',
  TimeZone.europeSlashMariehamn: 'Europe/Mariehamn',
  TimeZone.europeSlashMinsk: 'Europe/Minsk',
  TimeZone.europeSlashMonaco: 'Europe/Monaco',
  TimeZone.europeSlashMoscow: 'Europe/Moscow',
  TimeZone.europeSlashNicosia: 'Europe/Nicosia',
  TimeZone.europeSlashOslo: 'Europe/Oslo',
  TimeZone.europeSlashParis: 'Europe/Paris',
  TimeZone.europeSlashPodgorica: 'Europe/Podgorica',
  TimeZone.europeSlashPrague: 'Europe/Prague',
  TimeZone.europeSlashRiga: 'Europe/Riga',
  TimeZone.europeSlashRome: 'Europe/Rome',
  TimeZone.europeSlashSamara: 'Europe/Samara',
  TimeZone.europeSlashSanMarino: 'Europe/San_Marino',
  TimeZone.europeSlashSarajevo: 'Europe/Sarajevo',
  TimeZone.europeSlashSaratov: 'Europe/Saratov',
  TimeZone.europeSlashSimferopol: 'Europe/Simferopol',
  TimeZone.europeSlashSkopje: 'Europe/Skopje',
  TimeZone.europeSlashSofia: 'Europe/Sofia',
  TimeZone.europeSlashStockholm: 'Europe/Stockholm',
  TimeZone.europeSlashTallinn: 'Europe/Tallinn',
  TimeZone.europeSlashTirane: 'Europe/Tirane',
  TimeZone.europeSlashTiraspol: 'Europe/Tiraspol',
  TimeZone.europeSlashUlyanovsk: 'Europe/Ulyanovsk',
  TimeZone.europeSlashUzhgorod: 'Europe/Uzhgorod',
  TimeZone.europeSlashVaduz: 'Europe/Vaduz',
  TimeZone.europeSlashVatican: 'Europe/Vatican',
  TimeZone.europeSlashVienna: 'Europe/Vienna',
  TimeZone.europeSlashVilnius: 'Europe/Vilnius',
  TimeZone.europeSlashVolgograd: 'Europe/Volgograd',
  TimeZone.europeSlashWarsaw: 'Europe/Warsaw',
  TimeZone.europeSlashZagreb: 'Europe/Zagreb',
  TimeZone.europeSlashZaporozhye: 'Europe/Zaporozhye',
  TimeZone.europeSlashZurich: 'Europe/Zurich',
  TimeZone.GB: 'GB',
  TimeZone.gBEire: 'GB-Eire',
  TimeZone.GMT: 'GMT',
  TimeZone.gMTPlus0: 'GMT+0',
  TimeZone.gMT0: 'GMT-0',
  TimeZone.gMT02: 'GMT0',
  TimeZone.greenwich: 'Greenwich',
  TimeZone.HST: 'HST',
  TimeZone.hongkong: 'Hongkong',
  TimeZone.iceland: 'Iceland',
  TimeZone.indianSlashAntananarivo: 'Indian/Antananarivo',
  TimeZone.indianSlashChagos: 'Indian/Chagos',
  TimeZone.indianSlashChristmas: 'Indian/Christmas',
  TimeZone.indianSlashCocos: 'Indian/Cocos',
  TimeZone.indianSlashComoro: 'Indian/Comoro',
  TimeZone.indianSlashKerguelen: 'Indian/Kerguelen',
  TimeZone.indianSlashMahe: 'Indian/Mahe',
  TimeZone.indianSlashMaldives: 'Indian/Maldives',
  TimeZone.indianSlashMauritius: 'Indian/Mauritius',
  TimeZone.indianSlashMayotte: 'Indian/Mayotte',
  TimeZone.indianSlashReunion: 'Indian/Reunion',
  TimeZone.iran: 'Iran',
  TimeZone.israel: 'Israel',
  TimeZone.jamaica: 'Jamaica',
  TimeZone.japan: 'Japan',
  TimeZone.kwajalein: 'Kwajalein',
  TimeZone.libya: 'Libya',
  TimeZone.MET: 'MET',
  TimeZone.MST: 'MST',
  TimeZone.mST7MDT: 'MST7MDT',
  TimeZone.mexicoSlashBajaNorte: 'Mexico/BajaNorte',
  TimeZone.mexicoSlashBajaSur: 'Mexico/BajaSur',
  TimeZone.mexicoSlashGeneral: 'Mexico/General',
  TimeZone.NZ: 'NZ',
  TimeZone.NZ_CHAT: 'NZ-CHAT',
  TimeZone.navajo: 'Navajo',
  TimeZone.PRC: 'PRC',
  TimeZone.pST8PDT: 'PST8PDT',
  TimeZone.pacificSlashApia: 'Pacific/Apia',
  TimeZone.pacificSlashAuckland: 'Pacific/Auckland',
  TimeZone.pacificSlashBougainville: 'Pacific/Bougainville',
  TimeZone.pacificSlashChatham: 'Pacific/Chatham',
  TimeZone.pacificSlashChuuk: 'Pacific/Chuuk',
  TimeZone.pacificSlashEaster: 'Pacific/Easter',
  TimeZone.pacificSlashEfate: 'Pacific/Efate',
  TimeZone.pacificSlashEnderbury: 'Pacific/Enderbury',
  TimeZone.pacificSlashFakaofo: 'Pacific/Fakaofo',
  TimeZone.pacificSlashFiji: 'Pacific/Fiji',
  TimeZone.pacificSlashFunafuti: 'Pacific/Funafuti',
  TimeZone.pacificSlashGalapagos: 'Pacific/Galapagos',
  TimeZone.pacificSlashGambier: 'Pacific/Gambier',
  TimeZone.pacificSlashGuadalcanal: 'Pacific/Guadalcanal',
  TimeZone.pacificSlashGuam: 'Pacific/Guam',
  TimeZone.pacificSlashHonolulu: 'Pacific/Honolulu',
  TimeZone.pacificSlashJohnston: 'Pacific/Johnston',
  TimeZone.pacificSlashKiritimati: 'Pacific/Kiritimati',
  TimeZone.pacificSlashKosrae: 'Pacific/Kosrae',
  TimeZone.pacificSlashKwajalein: 'Pacific/Kwajalein',
  TimeZone.pacificSlashMajuro: 'Pacific/Majuro',
  TimeZone.pacificSlashMarquesas: 'Pacific/Marquesas',
  TimeZone.pacificSlashMidway: 'Pacific/Midway',
  TimeZone.pacificSlashNauru: 'Pacific/Nauru',
  TimeZone.pacificSlashNiue: 'Pacific/Niue',
  TimeZone.pacificSlashNorfolk: 'Pacific/Norfolk',
  TimeZone.pacificSlashNoumea: 'Pacific/Noumea',
  TimeZone.pacificSlashPagoPago: 'Pacific/Pago_Pago',
  TimeZone.pacificSlashPalau: 'Pacific/Palau',
  TimeZone.pacificSlashPitcairn: 'Pacific/Pitcairn',
  TimeZone.pacificSlashPohnpei: 'Pacific/Pohnpei',
  TimeZone.pacificSlashPonape: 'Pacific/Ponape',
  TimeZone.pacificSlashPortMoresby: 'Pacific/Port_Moresby',
  TimeZone.pacificSlashRarotonga: 'Pacific/Rarotonga',
  TimeZone.pacificSlashSaipan: 'Pacific/Saipan',
  TimeZone.pacificSlashSamoa: 'Pacific/Samoa',
  TimeZone.pacificSlashTahiti: 'Pacific/Tahiti',
  TimeZone.pacificSlashTarawa: 'Pacific/Tarawa',
  TimeZone.pacificSlashTongatapu: 'Pacific/Tongatapu',
  TimeZone.pacificSlashTruk: 'Pacific/Truk',
  TimeZone.pacificSlashWake: 'Pacific/Wake',
  TimeZone.pacificSlashWallis: 'Pacific/Wallis',
  TimeZone.pacificSlashYap: 'Pacific/Yap',
  TimeZone.poland: 'Poland',
  TimeZone.portugal: 'Portugal',
  TimeZone.ROC: 'ROC',
  TimeZone.ROK: 'ROK',
  TimeZone.singapore: 'Singapore',
  TimeZone.turkey: 'Turkey',
  TimeZone.UCT: 'UCT',
  TimeZone.uSSlashAlaska: 'US/Alaska',
  TimeZone.uSSlashAleutian: 'US/Aleutian',
  TimeZone.uSSlashArizona: 'US/Arizona',
  TimeZone.uSSlashCentral: 'US/Central',
  TimeZone.uSSlashEastIndiana: 'US/East-Indiana',
  TimeZone.uSSlashEastern: 'US/Eastern',
  TimeZone.uSSlashHawaii: 'US/Hawaii',
  TimeZone.uSSlashIndianaStarke: 'US/Indiana-Starke',
  TimeZone.uSSlashMichigan: 'US/Michigan',
  TimeZone.uSSlashMountain: 'US/Mountain',
  TimeZone.uSSlashPacific: 'US/Pacific',
  TimeZone.uSSlashSamoa: 'US/Samoa',
  TimeZone.UTC: 'UTC',
  TimeZone.universal: 'Universal',
  TimeZone.W_SU: 'W-SU',
  TimeZone.WET: 'WET',
  TimeZone.zulu: 'Zulu',
};

const _$DisplayDataModeEnumMap = {
  DisplayDataMode.power: 'power',
  DisplayDataMode.velocity: 'velocity',
};

const _$DisplayFocusModeEnumMap = {
  DisplayFocusMode.mean: 'mean',
  DisplayFocusMode.peak: 'peak',
};
