//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';


enum TimeZone {
  @JsonValue(r'Africa/Abidjan')
  africaSlashAbidjan,
  @JsonValue(r'Africa/Accra')
  africaSlashAccra,
  @JsonValue(r'Africa/Addis_Ababa')
  africaSlashAddisAbaba,
  @JsonValue(r'Africa/Algiers')
  africaSlashAlgiers,
  @JsonValue(r'Africa/Asmara')
  africaSlashAsmara,
  @JsonValue(r'Africa/Asmera')
  africaSlashAsmera,
  @JsonValue(r'Africa/Bamako')
  africaSlashBamako,
  @JsonValue(r'Africa/Bangui')
  africaSlashBangui,
  @JsonValue(r'Africa/Banjul')
  africaSlashBanjul,
  @JsonValue(r'Africa/Bissau')
  africaSlashBissau,
  @JsonValue(r'Africa/Blantyre')
  africaSlashBlantyre,
  @JsonValue(r'Africa/Brazzaville')
  africaSlashBrazzaville,
  @JsonValue(r'Africa/Bujumbura')
  africaSlashBujumbura,
  @JsonValue(r'Africa/Cairo')
  africaSlashCairo,
  @JsonValue(r'Africa/Casablanca')
  africaSlashCasablanca,
  @JsonValue(r'Africa/Ceuta')
  africaSlashCeuta,
  @JsonValue(r'Africa/Conakry')
  africaSlashConakry,
  @JsonValue(r'Africa/Dakar')
  africaSlashDakar,
  @JsonValue(r'Africa/Dar_es_Salaam')
  africaSlashDarEsSalaam,
  @JsonValue(r'Africa/Djibouti')
  africaSlashDjibouti,
  @JsonValue(r'Africa/Douala')
  africaSlashDouala,
  @JsonValue(r'Africa/El_Aaiun')
  africaSlashElAaiun,
  @JsonValue(r'Africa/Freetown')
  africaSlashFreetown,
  @JsonValue(r'Africa/Gaborone')
  africaSlashGaborone,
  @JsonValue(r'Africa/Harare')
  africaSlashHarare,
  @JsonValue(r'Africa/Johannesburg')
  africaSlashJohannesburg,
  @JsonValue(r'Africa/Juba')
  africaSlashJuba,
  @JsonValue(r'Africa/Kampala')
  africaSlashKampala,
  @JsonValue(r'Africa/Khartoum')
  africaSlashKhartoum,
  @JsonValue(r'Africa/Kigali')
  africaSlashKigali,
  @JsonValue(r'Africa/Kinshasa')
  africaSlashKinshasa,
  @JsonValue(r'Africa/Lagos')
  africaSlashLagos,
  @JsonValue(r'Africa/Libreville')
  africaSlashLibreville,
  @JsonValue(r'Africa/Lome')
  africaSlashLome,
  @JsonValue(r'Africa/Luanda')
  africaSlashLuanda,
  @JsonValue(r'Africa/Lubumbashi')
  africaSlashLubumbashi,
  @JsonValue(r'Africa/Lusaka')
  africaSlashLusaka,
  @JsonValue(r'Africa/Malabo')
  africaSlashMalabo,
  @JsonValue(r'Africa/Maputo')
  africaSlashMaputo,
  @JsonValue(r'Africa/Maseru')
  africaSlashMaseru,
  @JsonValue(r'Africa/Mbabane')
  africaSlashMbabane,
  @JsonValue(r'Africa/Mogadishu')
  africaSlashMogadishu,
  @JsonValue(r'Africa/Monrovia')
  africaSlashMonrovia,
  @JsonValue(r'Africa/Nairobi')
  africaSlashNairobi,
  @JsonValue(r'Africa/Ndjamena')
  africaSlashNdjamena,
  @JsonValue(r'Africa/Niamey')
  africaSlashNiamey,
  @JsonValue(r'Africa/Nouakchott')
  africaSlashNouakchott,
  @JsonValue(r'Africa/Ouagadougou')
  africaSlashOuagadougou,
  @JsonValue(r'Africa/Porto-Novo')
  africaSlashPortoNovo,
  @JsonValue(r'Africa/Sao_Tome')
  africaSlashSaoTome,
  @JsonValue(r'Africa/Timbuktu')
  africaSlashTimbuktu,
  @JsonValue(r'Africa/Tripoli')
  africaSlashTripoli,
  @JsonValue(r'Africa/Tunis')
  africaSlashTunis,
  @JsonValue(r'Africa/Windhoek')
  africaSlashWindhoek,
  @JsonValue(r'America/Adak')
  americaSlashAdak,
  @JsonValue(r'America/Anchorage')
  americaSlashAnchorage,
  @JsonValue(r'America/Anguilla')
  americaSlashAnguilla,
  @JsonValue(r'America/Antigua')
  americaSlashAntigua,
  @JsonValue(r'America/Araguaina')
  americaSlashAraguaina,
  @JsonValue(r'America/Argentina/Buenos_Aires')
  americaSlashArgentinaSlashBuenosAires,
  @JsonValue(r'America/Argentina/Catamarca')
  americaSlashArgentinaSlashCatamarca,
  @JsonValue(r'America/Argentina/ComodRivadavia')
  americaSlashArgentinaSlashComodRivadavia,
  @JsonValue(r'America/Argentina/Cordoba')
  americaSlashArgentinaSlashCordoba,
  @JsonValue(r'America/Argentina/Jujuy')
  americaSlashArgentinaSlashJujuy,
  @JsonValue(r'America/Argentina/La_Rioja')
  americaSlashArgentinaSlashLaRioja,
  @JsonValue(r'America/Argentina/Mendoza')
  americaSlashArgentinaSlashMendoza,
  @JsonValue(r'America/Argentina/Rio_Gallegos')
  americaSlashArgentinaSlashRioGallegos,
  @JsonValue(r'America/Argentina/Salta')
  americaSlashArgentinaSlashSalta,
  @JsonValue(r'America/Argentina/San_Juan')
  americaSlashArgentinaSlashSanJuan,
  @JsonValue(r'America/Argentina/San_Luis')
  americaSlashArgentinaSlashSanLuis,
  @JsonValue(r'America/Argentina/Tucuman')
  americaSlashArgentinaSlashTucuman,
  @JsonValue(r'America/Argentina/Ushuaia')
  americaSlashArgentinaSlashUshuaia,
  @JsonValue(r'America/Aruba')
  americaSlashAruba,
  @JsonValue(r'America/Asuncion')
  americaSlashAsuncion,
  @JsonValue(r'America/Atikokan')
  americaSlashAtikokan,
  @JsonValue(r'America/Atka')
  americaSlashAtka,
  @JsonValue(r'America/Bahia')
  americaSlashBahia,
  @JsonValue(r'America/Bahia_Banderas')
  americaSlashBahiaBanderas,
  @JsonValue(r'America/Barbados')
  americaSlashBarbados,
  @JsonValue(r'America/Belem')
  americaSlashBelem,
  @JsonValue(r'America/Belize')
  americaSlashBelize,
  @JsonValue(r'America/Blanc-Sablon')
  americaSlashBlancSablon,
  @JsonValue(r'America/Boa_Vista')
  americaSlashBoaVista,
  @JsonValue(r'America/Bogota')
  americaSlashBogota,
  @JsonValue(r'America/Boise')
  americaSlashBoise,
  @JsonValue(r'America/Buenos_Aires')
  americaSlashBuenosAires,
  @JsonValue(r'America/Cambridge_Bay')
  americaSlashCambridgeBay,
  @JsonValue(r'America/Campo_Grande')
  americaSlashCampoGrande,
  @JsonValue(r'America/Cancun')
  americaSlashCancun,
  @JsonValue(r'America/Caracas')
  americaSlashCaracas,
  @JsonValue(r'America/Catamarca')
  americaSlashCatamarca,
  @JsonValue(r'America/Cayenne')
  americaSlashCayenne,
  @JsonValue(r'America/Cayman')
  americaSlashCayman,
  @JsonValue(r'America/Chicago')
  americaSlashChicago,
  @JsonValue(r'America/Chihuahua')
  americaSlashChihuahua,
  @JsonValue(r'America/Coral_Harbour')
  americaSlashCoralHarbour,
  @JsonValue(r'America/Cordoba')
  americaSlashCordoba,
  @JsonValue(r'America/Costa_Rica')
  americaSlashCostaRica,
  @JsonValue(r'America/Creston')
  americaSlashCreston,
  @JsonValue(r'America/Cuiaba')
  americaSlashCuiaba,
  @JsonValue(r'America/Curacao')
  americaSlashCuracao,
  @JsonValue(r'America/Danmarkshavn')
  americaSlashDanmarkshavn,
  @JsonValue(r'America/Dawson')
  americaSlashDawson,
  @JsonValue(r'America/Dawson_Creek')
  americaSlashDawsonCreek,
  @JsonValue(r'America/Denver')
  americaSlashDenver,
  @JsonValue(r'America/Detroit')
  americaSlashDetroit,
  @JsonValue(r'America/Dominica')
  americaSlashDominica,
  @JsonValue(r'America/Edmonton')
  americaSlashEdmonton,
  @JsonValue(r'America/Eirunepe')
  americaSlashEirunepe,
  @JsonValue(r'America/El_Salvador')
  americaSlashElSalvador,
  @JsonValue(r'America/Ensenada')
  americaSlashEnsenada,
  @JsonValue(r'America/Fort_Nelson')
  americaSlashFortNelson,
  @JsonValue(r'America/Fort_Wayne')
  americaSlashFortWayne,
  @JsonValue(r'America/Fortaleza')
  americaSlashFortaleza,
  @JsonValue(r'America/Glace_Bay')
  americaSlashGlaceBay,
  @JsonValue(r'America/Godthab')
  americaSlashGodthab,
  @JsonValue(r'America/Goose_Bay')
  americaSlashGooseBay,
  @JsonValue(r'America/Grand_Turk')
  americaSlashGrandTurk,
  @JsonValue(r'America/Grenada')
  americaSlashGrenada,
  @JsonValue(r'America/Guadeloupe')
  americaSlashGuadeloupe,
  @JsonValue(r'America/Guatemala')
  americaSlashGuatemala,
  @JsonValue(r'America/Guayaquil')
  americaSlashGuayaquil,
  @JsonValue(r'America/Guyana')
  americaSlashGuyana,
  @JsonValue(r'America/Halifax')
  americaSlashHalifax,
  @JsonValue(r'America/Havana')
  americaSlashHavana,
  @JsonValue(r'America/Hermosillo')
  americaSlashHermosillo,
  @JsonValue(r'America/Indiana/Indianapolis')
  americaSlashIndianaSlashIndianapolis,
  @JsonValue(r'America/Indiana/Knox')
  americaSlashIndianaSlashKnox,
  @JsonValue(r'America/Indiana/Marengo')
  americaSlashIndianaSlashMarengo,
  @JsonValue(r'America/Indiana/Petersburg')
  americaSlashIndianaSlashPetersburg,
  @JsonValue(r'America/Indiana/Tell_City')
  americaSlashIndianaSlashTellCity,
  @JsonValue(r'America/Indiana/Vevay')
  americaSlashIndianaSlashVevay,
  @JsonValue(r'America/Indiana/Vincennes')
  americaSlashIndianaSlashVincennes,
  @JsonValue(r'America/Indiana/Winamac')
  americaSlashIndianaSlashWinamac,
  @JsonValue(r'America/Indianapolis')
  americaSlashIndianapolis,
  @JsonValue(r'America/Inuvik')
  americaSlashInuvik,
  @JsonValue(r'America/Iqaluit')
  americaSlashIqaluit,
  @JsonValue(r'America/Jamaica')
  americaSlashJamaica,
  @JsonValue(r'America/Jujuy')
  americaSlashJujuy,
  @JsonValue(r'America/Juneau')
  americaSlashJuneau,
  @JsonValue(r'America/Kentucky/Louisville')
  americaSlashKentuckySlashLouisville,
  @JsonValue(r'America/Kentucky/Monticello')
  americaSlashKentuckySlashMonticello,
  @JsonValue(r'America/Knox_IN')
  americaSlashKnoxIN,
  @JsonValue(r'America/Kralendijk')
  americaSlashKralendijk,
  @JsonValue(r'America/La_Paz')
  americaSlashLaPaz,
  @JsonValue(r'America/Lima')
  americaSlashLima,
  @JsonValue(r'America/Los_Angeles')
  americaSlashLosAngeles,
  @JsonValue(r'America/Louisville')
  americaSlashLouisville,
  @JsonValue(r'America/Lower_Princes')
  americaSlashLowerPrinces,
  @JsonValue(r'America/Maceio')
  americaSlashMaceio,
  @JsonValue(r'America/Managua')
  americaSlashManagua,
  @JsonValue(r'America/Manaus')
  americaSlashManaus,
  @JsonValue(r'America/Marigot')
  americaSlashMarigot,
  @JsonValue(r'America/Martinique')
  americaSlashMartinique,
  @JsonValue(r'America/Matamoros')
  americaSlashMatamoros,
  @JsonValue(r'America/Mazatlan')
  americaSlashMazatlan,
  @JsonValue(r'America/Mendoza')
  americaSlashMendoza,
  @JsonValue(r'America/Menominee')
  americaSlashMenominee,
  @JsonValue(r'America/Merida')
  americaSlashMerida,
  @JsonValue(r'America/Metlakatla')
  americaSlashMetlakatla,
  @JsonValue(r'America/Mexico_City')
  americaSlashMexicoCity,
  @JsonValue(r'America/Miquelon')
  americaSlashMiquelon,
  @JsonValue(r'America/Moncton')
  americaSlashMoncton,
  @JsonValue(r'America/Monterrey')
  americaSlashMonterrey,
  @JsonValue(r'America/Montevideo')
  americaSlashMontevideo,
  @JsonValue(r'America/Montreal')
  americaSlashMontreal,
  @JsonValue(r'America/Montserrat')
  americaSlashMontserrat,
  @JsonValue(r'America/Nassau')
  americaSlashNassau,
  @JsonValue(r'America/New_York')
  americaSlashNewYork,
  @JsonValue(r'America/Nipigon')
  americaSlashNipigon,
  @JsonValue(r'America/Nome')
  americaSlashNome,
  @JsonValue(r'America/Noronha')
  americaSlashNoronha,
  @JsonValue(r'America/North_Dakota/Beulah')
  americaSlashNorthDakotaSlashBeulah,
  @JsonValue(r'America/North_Dakota/Center')
  americaSlashNorthDakotaSlashCenter,
  @JsonValue(r'America/North_Dakota/New_Salem')
  americaSlashNorthDakotaSlashNewSalem,
  @JsonValue(r'America/Ojinaga')
  americaSlashOjinaga,
  @JsonValue(r'America/Panama')
  americaSlashPanama,
  @JsonValue(r'America/Pangnirtung')
  americaSlashPangnirtung,
  @JsonValue(r'America/Paramaribo')
  americaSlashParamaribo,
  @JsonValue(r'America/Phoenix')
  americaSlashPhoenix,
  @JsonValue(r'America/Port-au-Prince')
  americaSlashPortAuPrince,
  @JsonValue(r'America/Port_of_Spain')
  americaSlashPortOfSpain,
  @JsonValue(r'America/Porto_Acre')
  americaSlashPortoAcre,
  @JsonValue(r'America/Porto_Velho')
  americaSlashPortoVelho,
  @JsonValue(r'America/Puerto_Rico')
  americaSlashPuertoRico,
  @JsonValue(r'America/Rainy_River')
  americaSlashRainyRiver,
  @JsonValue(r'America/Rankin_Inlet')
  americaSlashRankinInlet,
  @JsonValue(r'America/Recife')
  americaSlashRecife,
  @JsonValue(r'America/Regina')
  americaSlashRegina,
  @JsonValue(r'America/Resolute')
  americaSlashResolute,
  @JsonValue(r'America/Rio_Branco')
  americaSlashRioBranco,
  @JsonValue(r'America/Rosario')
  americaSlashRosario,
  @JsonValue(r'America/Santa_Isabel')
  americaSlashSantaIsabel,
  @JsonValue(r'America/Santarem')
  americaSlashSantarem,
  @JsonValue(r'America/Santiago')
  americaSlashSantiago,
  @JsonValue(r'America/Santo_Domingo')
  americaSlashSantoDomingo,
  @JsonValue(r'America/Sao_Paulo')
  americaSlashSaoPaulo,
  @JsonValue(r'America/Scoresbysund')
  americaSlashScoresbysund,
  @JsonValue(r'America/Shiprock')
  americaSlashShiprock,
  @JsonValue(r'America/Sitka')
  americaSlashSitka,
  @JsonValue(r'America/St_Barthelemy')
  americaSlashStBarthelemy,
  @JsonValue(r'America/St_Johns')
  americaSlashStJohns,
  @JsonValue(r'America/St_Kitts')
  americaSlashStKitts,
  @JsonValue(r'America/St_Lucia')
  americaSlashStLucia,
  @JsonValue(r'America/St_Thomas')
  americaSlashStThomas,
  @JsonValue(r'America/St_Vincent')
  americaSlashStVincent,
  @JsonValue(r'America/Swift_Current')
  americaSlashSwiftCurrent,
  @JsonValue(r'America/Tegucigalpa')
  americaSlashTegucigalpa,
  @JsonValue(r'America/Thule')
  americaSlashThule,
  @JsonValue(r'America/Thunder_Bay')
  americaSlashThunderBay,
  @JsonValue(r'America/Tijuana')
  americaSlashTijuana,
  @JsonValue(r'America/Toronto')
  americaSlashToronto,
  @JsonValue(r'America/Tortola')
  americaSlashTortola,
  @JsonValue(r'America/Vancouver')
  americaSlashVancouver,
  @JsonValue(r'America/Virgin')
  americaSlashVirgin,
  @JsonValue(r'America/Whitehorse')
  americaSlashWhitehorse,
  @JsonValue(r'America/Winnipeg')
  americaSlashWinnipeg,
  @JsonValue(r'America/Yakutat')
  americaSlashYakutat,
  @JsonValue(r'America/Yellowknife')
  americaSlashYellowknife,
  @JsonValue(r'Antarctica/Casey')
  antarcticaSlashCasey,
  @JsonValue(r'Antarctica/Davis')
  antarcticaSlashDavis,
  @JsonValue(r'Antarctica/DumontDUrville')
  antarcticaSlashDumontDUrville,
  @JsonValue(r'Antarctica/Macquarie')
  antarcticaSlashMacquarie,
  @JsonValue(r'Antarctica/Mawson')
  antarcticaSlashMawson,
  @JsonValue(r'Antarctica/McMurdo')
  antarcticaSlashMcMurdo,
  @JsonValue(r'Antarctica/Palmer')
  antarcticaSlashPalmer,
  @JsonValue(r'Antarctica/Rothera')
  antarcticaSlashRothera,
  @JsonValue(r'Antarctica/South_Pole')
  antarcticaSlashSouthPole,
  @JsonValue(r'Antarctica/Syowa')
  antarcticaSlashSyowa,
  @JsonValue(r'Antarctica/Troll')
  antarcticaSlashTroll,
  @JsonValue(r'Antarctica/Vostok')
  antarcticaSlashVostok,
  @JsonValue(r'Arctic/Longyearbyen')
  arcticSlashLongyearbyen,
  @JsonValue(r'Asia/Aden')
  asiaSlashAden,
  @JsonValue(r'Asia/Almaty')
  asiaSlashAlmaty,
  @JsonValue(r'Asia/Amman')
  asiaSlashAmman,
  @JsonValue(r'Asia/Anadyr')
  asiaSlashAnadyr,
  @JsonValue(r'Asia/Aqtau')
  asiaSlashAqtau,
  @JsonValue(r'Asia/Aqtobe')
  asiaSlashAqtobe,
  @JsonValue(r'Asia/Ashgabat')
  asiaSlashAshgabat,
  @JsonValue(r'Asia/Ashkhabad')
  asiaSlashAshkhabad,
  @JsonValue(r'Asia/Atyrau')
  asiaSlashAtyrau,
  @JsonValue(r'Asia/Baghdad')
  asiaSlashBaghdad,
  @JsonValue(r'Asia/Bahrain')
  asiaSlashBahrain,
  @JsonValue(r'Asia/Baku')
  asiaSlashBaku,
  @JsonValue(r'Asia/Bangkok')
  asiaSlashBangkok,
  @JsonValue(r'Asia/Barnaul')
  asiaSlashBarnaul,
  @JsonValue(r'Asia/Beirut')
  asiaSlashBeirut,
  @JsonValue(r'Asia/Bishkek')
  asiaSlashBishkek,
  @JsonValue(r'Asia/Brunei')
  asiaSlashBrunei,
  @JsonValue(r'Asia/Calcutta')
  asiaSlashCalcutta,
  @JsonValue(r'Asia/Chita')
  asiaSlashChita,
  @JsonValue(r'Asia/Choibalsan')
  asiaSlashChoibalsan,
  @JsonValue(r'Asia/Chongqing')
  asiaSlashChongqing,
  @JsonValue(r'Asia/Chungking')
  asiaSlashChungking,
  @JsonValue(r'Asia/Colombo')
  asiaSlashColombo,
  @JsonValue(r'Asia/Dacca')
  asiaSlashDacca,
  @JsonValue(r'Asia/Damascus')
  asiaSlashDamascus,
  @JsonValue(r'Asia/Dhaka')
  asiaSlashDhaka,
  @JsonValue(r'Asia/Dili')
  asiaSlashDili,
  @JsonValue(r'Asia/Dubai')
  asiaSlashDubai,
  @JsonValue(r'Asia/Dushanbe')
  asiaSlashDushanbe,
  @JsonValue(r'Asia/Famagusta')
  asiaSlashFamagusta,
  @JsonValue(r'Asia/Gaza')
  asiaSlashGaza,
  @JsonValue(r'Asia/Hanoi')
  asiaSlashHanoi,
  @JsonValue(r'Asia/Harbin')
  asiaSlashHarbin,
  @JsonValue(r'Asia/Hebron')
  asiaSlashHebron,
  @JsonValue(r'Asia/Ho_Chi_Minh')
  asiaSlashHoChiMinh,
  @JsonValue(r'Asia/Hong_Kong')
  asiaSlashHongKong,
  @JsonValue(r'Asia/Hovd')
  asiaSlashHovd,
  @JsonValue(r'Asia/Irkutsk')
  asiaSlashIrkutsk,
  @JsonValue(r'Asia/Istanbul')
  asiaSlashIstanbul,
  @JsonValue(r'Asia/Jakarta')
  asiaSlashJakarta,
  @JsonValue(r'Asia/Jayapura')
  asiaSlashJayapura,
  @JsonValue(r'Asia/Jerusalem')
  asiaSlashJerusalem,
  @JsonValue(r'Asia/Kabul')
  asiaSlashKabul,
  @JsonValue(r'Asia/Kamchatka')
  asiaSlashKamchatka,
  @JsonValue(r'Asia/Karachi')
  asiaSlashKarachi,
  @JsonValue(r'Asia/Kashgar')
  asiaSlashKashgar,
  @JsonValue(r'Asia/Kathmandu')
  asiaSlashKathmandu,
  @JsonValue(r'Asia/Katmandu')
  asiaSlashKatmandu,
  @JsonValue(r'Asia/Khandyga')
  asiaSlashKhandyga,
  @JsonValue(r'Asia/Kolkata')
  asiaSlashKolkata,
  @JsonValue(r'Asia/Krasnoyarsk')
  asiaSlashKrasnoyarsk,
  @JsonValue(r'Asia/Kuala_Lumpur')
  asiaSlashKualaLumpur,
  @JsonValue(r'Asia/Kuching')
  asiaSlashKuching,
  @JsonValue(r'Asia/Kuwait')
  asiaSlashKuwait,
  @JsonValue(r'Asia/Macao')
  asiaSlashMacao,
  @JsonValue(r'Asia/Macau')
  asiaSlashMacau,
  @JsonValue(r'Asia/Magadan')
  asiaSlashMagadan,
  @JsonValue(r'Asia/Makassar')
  asiaSlashMakassar,
  @JsonValue(r'Asia/Manila')
  asiaSlashManila,
  @JsonValue(r'Asia/Muscat')
  asiaSlashMuscat,
  @JsonValue(r'Asia/Nicosia')
  asiaSlashNicosia,
  @JsonValue(r'Asia/Novokuznetsk')
  asiaSlashNovokuznetsk,
  @JsonValue(r'Asia/Novosibirsk')
  asiaSlashNovosibirsk,
  @JsonValue(r'Asia/Omsk')
  asiaSlashOmsk,
  @JsonValue(r'Asia/Oral')
  asiaSlashOral,
  @JsonValue(r'Asia/Phnom_Penh')
  asiaSlashPhnomPenh,
  @JsonValue(r'Asia/Pontianak')
  asiaSlashPontianak,
  @JsonValue(r'Asia/Pyongyang')
  asiaSlashPyongyang,
  @JsonValue(r'Asia/Qatar')
  asiaSlashQatar,
  @JsonValue(r'Asia/Qyzylorda')
  asiaSlashQyzylorda,
  @JsonValue(r'Asia/Rangoon')
  asiaSlashRangoon,
  @JsonValue(r'Asia/Riyadh')
  asiaSlashRiyadh,
  @JsonValue(r'Asia/Saigon')
  asiaSlashSaigon,
  @JsonValue(r'Asia/Sakhalin')
  asiaSlashSakhalin,
  @JsonValue(r'Asia/Samarkand')
  asiaSlashSamarkand,
  @JsonValue(r'Asia/Seoul')
  asiaSlashSeoul,
  @JsonValue(r'Asia/Shanghai')
  asiaSlashShanghai,
  @JsonValue(r'Asia/Singapore')
  asiaSlashSingapore,
  @JsonValue(r'Asia/Srednekolymsk')
  asiaSlashSrednekolymsk,
  @JsonValue(r'Asia/Taipei')
  asiaSlashTaipei,
  @JsonValue(r'Asia/Tashkent')
  asiaSlashTashkent,
  @JsonValue(r'Asia/Tbilisi')
  asiaSlashTbilisi,
  @JsonValue(r'Asia/Tehran')
  asiaSlashTehran,
  @JsonValue(r'Asia/Tel_Aviv')
  asiaSlashTelAviv,
  @JsonValue(r'Asia/Thimbu')
  asiaSlashThimbu,
  @JsonValue(r'Asia/Thimphu')
  asiaSlashThimphu,
  @JsonValue(r'Asia/Tokyo')
  asiaSlashTokyo,
  @JsonValue(r'Asia/Tomsk')
  asiaSlashTomsk,
  @JsonValue(r'Asia/Ujung_Pandang')
  asiaSlashUjungPandang,
  @JsonValue(r'Asia/Ulaanbaatar')
  asiaSlashUlaanbaatar,
  @JsonValue(r'Asia/Ulan_Bator')
  asiaSlashUlanBator,
  @JsonValue(r'Asia/Urumqi')
  asiaSlashUrumqi,
  @JsonValue(r'Asia/Ust-Nera')
  asiaSlashUstNera,
  @JsonValue(r'Asia/Vientiane')
  asiaSlashVientiane,
  @JsonValue(r'Asia/Vladivostok')
  asiaSlashVladivostok,
  @JsonValue(r'Asia/Yakutsk')
  asiaSlashYakutsk,
  @JsonValue(r'Asia/Yangon')
  asiaSlashYangon,
  @JsonValue(r'Asia/Yekaterinburg')
  asiaSlashYekaterinburg,
  @JsonValue(r'Asia/Yerevan')
  asiaSlashYerevan,
  @JsonValue(r'Atlantic/Azores')
  atlanticSlashAzores,
  @JsonValue(r'Atlantic/Bermuda')
  atlanticSlashBermuda,
  @JsonValue(r'Atlantic/Canary')
  atlanticSlashCanary,
  @JsonValue(r'Atlantic/Cape_Verde')
  atlanticSlashCapeVerde,
  @JsonValue(r'Atlantic/Faeroe')
  atlanticSlashFaeroe,
  @JsonValue(r'Atlantic/Faroe')
  atlanticSlashFaroe,
  @JsonValue(r'Atlantic/Jan_Mayen')
  atlanticSlashJanMayen,
  @JsonValue(r'Atlantic/Madeira')
  atlanticSlashMadeira,
  @JsonValue(r'Atlantic/Reykjavik')
  atlanticSlashReykjavik,
  @JsonValue(r'Atlantic/South_Georgia')
  atlanticSlashSouthGeorgia,
  @JsonValue(r'Atlantic/St_Helena')
  atlanticSlashStHelena,
  @JsonValue(r'Atlantic/Stanley')
  atlanticSlashStanley,
  @JsonValue(r'Australia/ACT')
  australiaSlashACT,
  @JsonValue(r'Australia/Adelaide')
  australiaSlashAdelaide,
  @JsonValue(r'Australia/Brisbane')
  australiaSlashBrisbane,
  @JsonValue(r'Australia/Broken_Hill')
  australiaSlashBrokenHill,
  @JsonValue(r'Australia/Canberra')
  australiaSlashCanberra,
  @JsonValue(r'Australia/Currie')
  australiaSlashCurrie,
  @JsonValue(r'Australia/Darwin')
  australiaSlashDarwin,
  @JsonValue(r'Australia/Eucla')
  australiaSlashEucla,
  @JsonValue(r'Australia/Hobart')
  australiaSlashHobart,
  @JsonValue(r'Australia/LHI')
  australiaSlashLHI,
  @JsonValue(r'Australia/Lindeman')
  australiaSlashLindeman,
  @JsonValue(r'Australia/Lord_Howe')
  australiaSlashLordHowe,
  @JsonValue(r'Australia/Melbourne')
  australiaSlashMelbourne,
  @JsonValue(r'Australia/NSW')
  australiaSlashNSW,
  @JsonValue(r'Australia/North')
  australiaSlashNorth,
  @JsonValue(r'Australia/Perth')
  australiaSlashPerth,
  @JsonValue(r'Australia/Queensland')
  australiaSlashQueensland,
  @JsonValue(r'Australia/South')
  australiaSlashSouth,
  @JsonValue(r'Australia/Sydney')
  australiaSlashSydney,
  @JsonValue(r'Australia/Tasmania')
  australiaSlashTasmania,
  @JsonValue(r'Australia/Victoria')
  australiaSlashVictoria,
  @JsonValue(r'Australia/West')
  australiaSlashWest,
  @JsonValue(r'Australia/Yancowinna')
  australiaSlashYancowinna,
  @JsonValue(r'Brazil/Acre')
  brazilSlashAcre,
  @JsonValue(r'Brazil/DeNoronha')
  brazilSlashDeNoronha,
  @JsonValue(r'Brazil/East')
  brazilSlashEast,
  @JsonValue(r'Brazil/West')
  brazilSlashWest,
  @JsonValue(r'CET')
  CET,
  @JsonValue(r'CST6CDT')
  cST6CDT,
  @JsonValue(r'Canada/Atlantic')
  canadaSlashAtlantic,
  @JsonValue(r'Canada/Central')
  canadaSlashCentral,
  @JsonValue(r'Canada/East-Saskatchewan')
  canadaSlashEastSaskatchewan,
  @JsonValue(r'Canada/Eastern')
  canadaSlashEastern,
  @JsonValue(r'Canada/Mountain')
  canadaSlashMountain,
  @JsonValue(r'Canada/Newfoundland')
  canadaSlashNewfoundland,
  @JsonValue(r'Canada/Pacific')
  canadaSlashPacific,
  @JsonValue(r'Canada/Saskatchewan')
  canadaSlashSaskatchewan,
  @JsonValue(r'Canada/Yukon')
  canadaSlashYukon,
  @JsonValue(r'Chile/Continental')
  chileSlashContinental,
  @JsonValue(r'Chile/EasterIsland')
  chileSlashEasterIsland,
  @JsonValue(r'Cuba')
  cuba,
  @JsonValue(r'EET')
  EET,
  @JsonValue(r'EST')
  EST,
  @JsonValue(r'EST5EDT')
  eST5EDT,
  @JsonValue(r'Egypt')
  egypt,
  @JsonValue(r'Eire')
  eire,
  @JsonValue(r'Etc/GMT')
  etcSlashGMT,
  @JsonValue(r'Etc/GMT+0')
  etcSlashGMTPlus0,
  @JsonValue(r'Etc/GMT+1')
  etcSlashGMTPlus1,
  @JsonValue(r'Etc/GMT+10')
  etcSlashGMTPlus10,
  @JsonValue(r'Etc/GMT+11')
  etcSlashGMTPlus11,
  @JsonValue(r'Etc/GMT+12')
  etcSlashGMTPlus12,
  @JsonValue(r'Etc/GMT+2')
  etcSlashGMTPlus2,
  @JsonValue(r'Etc/GMT+3')
  etcSlashGMTPlus3,
  @JsonValue(r'Etc/GMT+4')
  etcSlashGMTPlus4,
  @JsonValue(r'Etc/GMT+5')
  etcSlashGMTPlus5,
  @JsonValue(r'Etc/GMT+6')
  etcSlashGMTPlus6,
  @JsonValue(r'Etc/GMT+7')
  etcSlashGMTPlus7,
  @JsonValue(r'Etc/GMT+8')
  etcSlashGMTPlus8,
  @JsonValue(r'Etc/GMT+9')
  etcSlashGMTPlus9,
  @JsonValue(r'Etc/GMT-0')
  etcSlashGMT0,
  @JsonValue(r'Etc/GMT-1')
  etcSlashGMT1,
  @JsonValue(r'Etc/GMT-10')
  etcSlashGMT10,
  @JsonValue(r'Etc/GMT-11')
  etcSlashGMT11,
  @JsonValue(r'Etc/GMT-12')
  etcSlashGMT12,
  @JsonValue(r'Etc/GMT-13')
  etcSlashGMT13,
  @JsonValue(r'Etc/GMT-14')
  etcSlashGMT14,
  @JsonValue(r'Etc/GMT-2')
  etcSlashGMT2,
  @JsonValue(r'Etc/GMT-3')
  etcSlashGMT3,
  @JsonValue(r'Etc/GMT-4')
  etcSlashGMT4,
  @JsonValue(r'Etc/GMT-5')
  etcSlashGMT5,
  @JsonValue(r'Etc/GMT-6')
  etcSlashGMT6,
  @JsonValue(r'Etc/GMT-7')
  etcSlashGMT7,
  @JsonValue(r'Etc/GMT-8')
  etcSlashGMT8,
  @JsonValue(r'Etc/GMT-9')
  etcSlashGMT9,
  @JsonValue(r'Etc/GMT0')
  etcSlashGMT02,
  @JsonValue(r'Etc/Greenwich')
  etcSlashGreenwich,
  @JsonValue(r'Etc/UCT')
  etcSlashUCT,
  @JsonValue(r'Etc/UTC')
  etcSlashUTC,
  @JsonValue(r'Etc/Universal')
  etcSlashUniversal,
  @JsonValue(r'Etc/Zulu')
  etcSlashZulu,
  @JsonValue(r'Europe/Amsterdam')
  europeSlashAmsterdam,
  @JsonValue(r'Europe/Andorra')
  europeSlashAndorra,
  @JsonValue(r'Europe/Astrakhan')
  europeSlashAstrakhan,
  @JsonValue(r'Europe/Athens')
  europeSlashAthens,
  @JsonValue(r'Europe/Belfast')
  europeSlashBelfast,
  @JsonValue(r'Europe/Belgrade')
  europeSlashBelgrade,
  @JsonValue(r'Europe/Berlin')
  europeSlashBerlin,
  @JsonValue(r'Europe/Bratislava')
  europeSlashBratislava,
  @JsonValue(r'Europe/Brussels')
  europeSlashBrussels,
  @JsonValue(r'Europe/Bucharest')
  europeSlashBucharest,
  @JsonValue(r'Europe/Budapest')
  europeSlashBudapest,
  @JsonValue(r'Europe/Busingen')
  europeSlashBusingen,
  @JsonValue(r'Europe/Chisinau')
  europeSlashChisinau,
  @JsonValue(r'Europe/Copenhagen')
  europeSlashCopenhagen,
  @JsonValue(r'Europe/Dublin')
  europeSlashDublin,
  @JsonValue(r'Europe/Gibraltar')
  europeSlashGibraltar,
  @JsonValue(r'Europe/Guernsey')
  europeSlashGuernsey,
  @JsonValue(r'Europe/Helsinki')
  europeSlashHelsinki,
  @JsonValue(r'Europe/Isle_of_Man')
  europeSlashIsleOfMan,
  @JsonValue(r'Europe/Istanbul')
  europeSlashIstanbul,
  @JsonValue(r'Europe/Jersey')
  europeSlashJersey,
  @JsonValue(r'Europe/Kaliningrad')
  europeSlashKaliningrad,
  @JsonValue(r'Europe/Kiev')
  europeSlashKiev,
  @JsonValue(r'Europe/Kirov')
  europeSlashKirov,
  @JsonValue(r'Europe/Lisbon')
  europeSlashLisbon,
  @JsonValue(r'Europe/Ljubljana')
  europeSlashLjubljana,
  @JsonValue(r'Europe/London')
  europeSlashLondon,
  @JsonValue(r'Europe/Luxembourg')
  europeSlashLuxembourg,
  @JsonValue(r'Europe/Madrid')
  europeSlashMadrid,
  @JsonValue(r'Europe/Malta')
  europeSlashMalta,
  @JsonValue(r'Europe/Mariehamn')
  europeSlashMariehamn,
  @JsonValue(r'Europe/Minsk')
  europeSlashMinsk,
  @JsonValue(r'Europe/Monaco')
  europeSlashMonaco,
  @JsonValue(r'Europe/Moscow')
  europeSlashMoscow,
  @JsonValue(r'Europe/Nicosia')
  europeSlashNicosia,
  @JsonValue(r'Europe/Oslo')
  europeSlashOslo,
  @JsonValue(r'Europe/Paris')
  europeSlashParis,
  @JsonValue(r'Europe/Podgorica')
  europeSlashPodgorica,
  @JsonValue(r'Europe/Prague')
  europeSlashPrague,
  @JsonValue(r'Europe/Riga')
  europeSlashRiga,
  @JsonValue(r'Europe/Rome')
  europeSlashRome,
  @JsonValue(r'Europe/Samara')
  europeSlashSamara,
  @JsonValue(r'Europe/San_Marino')
  europeSlashSanMarino,
  @JsonValue(r'Europe/Sarajevo')
  europeSlashSarajevo,
  @JsonValue(r'Europe/Saratov')
  europeSlashSaratov,
  @JsonValue(r'Europe/Simferopol')
  europeSlashSimferopol,
  @JsonValue(r'Europe/Skopje')
  europeSlashSkopje,
  @JsonValue(r'Europe/Sofia')
  europeSlashSofia,
  @JsonValue(r'Europe/Stockholm')
  europeSlashStockholm,
  @JsonValue(r'Europe/Tallinn')
  europeSlashTallinn,
  @JsonValue(r'Europe/Tirane')
  europeSlashTirane,
  @JsonValue(r'Europe/Tiraspol')
  europeSlashTiraspol,
  @JsonValue(r'Europe/Ulyanovsk')
  europeSlashUlyanovsk,
  @JsonValue(r'Europe/Uzhgorod')
  europeSlashUzhgorod,
  @JsonValue(r'Europe/Vaduz')
  europeSlashVaduz,
  @JsonValue(r'Europe/Vatican')
  europeSlashVatican,
  @JsonValue(r'Europe/Vienna')
  europeSlashVienna,
  @JsonValue(r'Europe/Vilnius')
  europeSlashVilnius,
  @JsonValue(r'Europe/Volgograd')
  europeSlashVolgograd,
  @JsonValue(r'Europe/Warsaw')
  europeSlashWarsaw,
  @JsonValue(r'Europe/Zagreb')
  europeSlashZagreb,
  @JsonValue(r'Europe/Zaporozhye')
  europeSlashZaporozhye,
  @JsonValue(r'Europe/Zurich')
  europeSlashZurich,
  @JsonValue(r'GB')
  GB,
  @JsonValue(r'GB-Eire')
  gBEire,
  @JsonValue(r'GMT')
  GMT,
  @JsonValue(r'GMT+0')
  gMTPlus0,
  @JsonValue(r'GMT-0')
  gMT0,
  @JsonValue(r'GMT0')
  gMT02,
  @JsonValue(r'Greenwich')
  greenwich,
  @JsonValue(r'HST')
  HST,
  @JsonValue(r'Hongkong')
  hongkong,
  @JsonValue(r'Iceland')
  iceland,
  @JsonValue(r'Indian/Antananarivo')
  indianSlashAntananarivo,
  @JsonValue(r'Indian/Chagos')
  indianSlashChagos,
  @JsonValue(r'Indian/Christmas')
  indianSlashChristmas,
  @JsonValue(r'Indian/Cocos')
  indianSlashCocos,
  @JsonValue(r'Indian/Comoro')
  indianSlashComoro,
  @JsonValue(r'Indian/Kerguelen')
  indianSlashKerguelen,
  @JsonValue(r'Indian/Mahe')
  indianSlashMahe,
  @JsonValue(r'Indian/Maldives')
  indianSlashMaldives,
  @JsonValue(r'Indian/Mauritius')
  indianSlashMauritius,
  @JsonValue(r'Indian/Mayotte')
  indianSlashMayotte,
  @JsonValue(r'Indian/Reunion')
  indianSlashReunion,
  @JsonValue(r'Iran')
  iran,
  @JsonValue(r'Israel')
  israel,
  @JsonValue(r'Jamaica')
  jamaica,
  @JsonValue(r'Japan')
  japan,
  @JsonValue(r'Kwajalein')
  kwajalein,
  @JsonValue(r'Libya')
  libya,
  @JsonValue(r'MET')
  MET,
  @JsonValue(r'MST')
  MST,
  @JsonValue(r'MST7MDT')
  mST7MDT,
  @JsonValue(r'Mexico/BajaNorte')
  mexicoSlashBajaNorte,
  @JsonValue(r'Mexico/BajaSur')
  mexicoSlashBajaSur,
  @JsonValue(r'Mexico/General')
  mexicoSlashGeneral,
  @JsonValue(r'NZ')
  NZ,
  @JsonValue(r'NZ-CHAT')
  NZ_CHAT,
  @JsonValue(r'Navajo')
  navajo,
  @JsonValue(r'PRC')
  PRC,
  @JsonValue(r'PST8PDT')
  pST8PDT,
  @JsonValue(r'Pacific/Apia')
  pacificSlashApia,
  @JsonValue(r'Pacific/Auckland')
  pacificSlashAuckland,
  @JsonValue(r'Pacific/Bougainville')
  pacificSlashBougainville,
  @JsonValue(r'Pacific/Chatham')
  pacificSlashChatham,
  @JsonValue(r'Pacific/Chuuk')
  pacificSlashChuuk,
  @JsonValue(r'Pacific/Easter')
  pacificSlashEaster,
  @JsonValue(r'Pacific/Efate')
  pacificSlashEfate,
  @JsonValue(r'Pacific/Enderbury')
  pacificSlashEnderbury,
  @JsonValue(r'Pacific/Fakaofo')
  pacificSlashFakaofo,
  @JsonValue(r'Pacific/Fiji')
  pacificSlashFiji,
  @JsonValue(r'Pacific/Funafuti')
  pacificSlashFunafuti,
  @JsonValue(r'Pacific/Galapagos')
  pacificSlashGalapagos,
  @JsonValue(r'Pacific/Gambier')
  pacificSlashGambier,
  @JsonValue(r'Pacific/Guadalcanal')
  pacificSlashGuadalcanal,
  @JsonValue(r'Pacific/Guam')
  pacificSlashGuam,
  @JsonValue(r'Pacific/Honolulu')
  pacificSlashHonolulu,
  @JsonValue(r'Pacific/Johnston')
  pacificSlashJohnston,
  @JsonValue(r'Pacific/Kiritimati')
  pacificSlashKiritimati,
  @JsonValue(r'Pacific/Kosrae')
  pacificSlashKosrae,
  @JsonValue(r'Pacific/Kwajalein')
  pacificSlashKwajalein,
  @JsonValue(r'Pacific/Majuro')
  pacificSlashMajuro,
  @JsonValue(r'Pacific/Marquesas')
  pacificSlashMarquesas,
  @JsonValue(r'Pacific/Midway')
  pacificSlashMidway,
  @JsonValue(r'Pacific/Nauru')
  pacificSlashNauru,
  @JsonValue(r'Pacific/Niue')
  pacificSlashNiue,
  @JsonValue(r'Pacific/Norfolk')
  pacificSlashNorfolk,
  @JsonValue(r'Pacific/Noumea')
  pacificSlashNoumea,
  @JsonValue(r'Pacific/Pago_Pago')
  pacificSlashPagoPago,
  @JsonValue(r'Pacific/Palau')
  pacificSlashPalau,
  @JsonValue(r'Pacific/Pitcairn')
  pacificSlashPitcairn,
  @JsonValue(r'Pacific/Pohnpei')
  pacificSlashPohnpei,
  @JsonValue(r'Pacific/Ponape')
  pacificSlashPonape,
  @JsonValue(r'Pacific/Port_Moresby')
  pacificSlashPortMoresby,
  @JsonValue(r'Pacific/Rarotonga')
  pacificSlashRarotonga,
  @JsonValue(r'Pacific/Saipan')
  pacificSlashSaipan,
  @JsonValue(r'Pacific/Samoa')
  pacificSlashSamoa,
  @JsonValue(r'Pacific/Tahiti')
  pacificSlashTahiti,
  @JsonValue(r'Pacific/Tarawa')
  pacificSlashTarawa,
  @JsonValue(r'Pacific/Tongatapu')
  pacificSlashTongatapu,
  @JsonValue(r'Pacific/Truk')
  pacificSlashTruk,
  @JsonValue(r'Pacific/Wake')
  pacificSlashWake,
  @JsonValue(r'Pacific/Wallis')
  pacificSlashWallis,
  @JsonValue(r'Pacific/Yap')
  pacificSlashYap,
  @JsonValue(r'Poland')
  poland,
  @JsonValue(r'Portugal')
  portugal,
  @JsonValue(r'ROC')
  ROC,
  @JsonValue(r'ROK')
  ROK,
  @JsonValue(r'Singapore')
  singapore,
  @JsonValue(r'Turkey')
  turkey,
  @JsonValue(r'UCT')
  UCT,
  @JsonValue(r'US/Alaska')
  uSSlashAlaska,
  @JsonValue(r'US/Aleutian')
  uSSlashAleutian,
  @JsonValue(r'US/Arizona')
  uSSlashArizona,
  @JsonValue(r'US/Central')
  uSSlashCentral,
  @JsonValue(r'US/East-Indiana')
  uSSlashEastIndiana,
  @JsonValue(r'US/Eastern')
  uSSlashEastern,
  @JsonValue(r'US/Hawaii')
  uSSlashHawaii,
  @JsonValue(r'US/Indiana-Starke')
  uSSlashIndianaStarke,
  @JsonValue(r'US/Michigan')
  uSSlashMichigan,
  @JsonValue(r'US/Mountain')
  uSSlashMountain,
  @JsonValue(r'US/Pacific')
  uSSlashPacific,
  @JsonValue(r'US/Samoa')
  uSSlashSamoa,
  @JsonValue(r'UTC')
  UTC,
  @JsonValue(r'Universal')
  universal,
  @JsonValue(r'W-SU')
  W_SU,
  @JsonValue(r'WET')
  WET,
  @JsonValue(r'Zulu')
  zulu,
}
