//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';


enum TimeZone {
  @JsonValue(r'Africa/Abidjan')
  Africa_Abidjan,
  @JsonValue(r'Africa/Accra')
  Africa_Accra,
  @JsonValue(r'Africa/Addis_Ababa')
  Africa_Addis_Ababa,
  @JsonValue(r'Africa/Algiers')
  Africa_Algiers,
  @JsonValue(r'Africa/Asmara')
  Africa_Asmara,
  @JsonValue(r'Africa/Asmera')
  Africa_Asmera,
  @JsonValue(r'Africa/Bamako')
  Africa_Bamako,
  @JsonValue(r'Africa/Bangui')
  Africa_Bangui,
  @JsonValue(r'Africa/Banjul')
  Africa_Banjul,
  @JsonValue(r'Africa/Bissau')
  Africa_Bissau,
  @JsonValue(r'Africa/Blantyre')
  Africa_Blantyre,
  @JsonValue(r'Africa/Brazzaville')
  Africa_Brazzaville,
  @JsonValue(r'Africa/Bujumbura')
  Africa_Bujumbura,
  @JsonValue(r'Africa/Cairo')
  Africa_Cairo,
  @JsonValue(r'Africa/Casablanca')
  Africa_Casablanca,
  @JsonValue(r'Africa/Ceuta')
  Africa_Ceuta,
  @JsonValue(r'Africa/Conakry')
  Africa_Conakry,
  @JsonValue(r'Africa/Dakar')
  Africa_Dakar,
  @JsonValue(r'Africa/Dar_es_Salaam')
  Africa_Dar_es_Salaam,
  @JsonValue(r'Africa/Djibouti')
  Africa_Djibouti,
  @JsonValue(r'Africa/Douala')
  Africa_Douala,
  @JsonValue(r'Africa/El_Aaiun')
  Africa_El_Aaiun,
  @JsonValue(r'Africa/Freetown')
  Africa_Freetown,
  @JsonValue(r'Africa/Gaborone')
  Africa_Gaborone,
  @JsonValue(r'Africa/Harare')
  Africa_Harare,
  @JsonValue(r'Africa/Johannesburg')
  Africa_Johannesburg,
  @JsonValue(r'Africa/Juba')
  Africa_Juba,
  @JsonValue(r'Africa/Kampala')
  Africa_Kampala,
  @JsonValue(r'Africa/Khartoum')
  Africa_Khartoum,
  @JsonValue(r'Africa/Kigali')
  Africa_Kigali,
  @JsonValue(r'Africa/Kinshasa')
  Africa_Kinshasa,
  @JsonValue(r'Africa/Lagos')
  Africa_Lagos,
  @JsonValue(r'Africa/Libreville')
  Africa_Libreville,
  @JsonValue(r'Africa/Lome')
  Africa_Lome,
  @JsonValue(r'Africa/Luanda')
  Africa_Luanda,
  @JsonValue(r'Africa/Lubumbashi')
  Africa_Lubumbashi,
  @JsonValue(r'Africa/Lusaka')
  Africa_Lusaka,
  @JsonValue(r'Africa/Malabo')
  Africa_Malabo,
  @JsonValue(r'Africa/Maputo')
  Africa_Maputo,
  @JsonValue(r'Africa/Maseru')
  Africa_Maseru,
  @JsonValue(r'Africa/Mbabane')
  Africa_Mbabane,
  @JsonValue(r'Africa/Mogadishu')
  Africa_Mogadishu,
  @JsonValue(r'Africa/Monrovia')
  Africa_Monrovia,
  @JsonValue(r'Africa/Nairobi')
  Africa_Nairobi,
  @JsonValue(r'Africa/Ndjamena')
  Africa_Ndjamena,
  @JsonValue(r'Africa/Niamey')
  Africa_Niamey,
  @JsonValue(r'Africa/Nouakchott')
  Africa_Nouakchott,
  @JsonValue(r'Africa/Ouagadougou')
  Africa_Ouagadougou,
  @JsonValue(r'Africa/Porto-Novo')
  Africa_PortoMinusNovo,
  @JsonValue(r'Africa/Sao_Tome')
  Africa_Sao_Tome,
  @JsonValue(r'Africa/Timbuktu')
  Africa_Timbuktu,
  @JsonValue(r'Africa/Tripoli')
  Africa_Tripoli,
  @JsonValue(r'Africa/Tunis')
  Africa_Tunis,
  @JsonValue(r'Africa/Windhoek')
  Africa_Windhoek,
  @JsonValue(r'America/Adak')
  America_Adak,
  @JsonValue(r'America/Anchorage')
  America_Anchorage,
  @JsonValue(r'America/Anguilla')
  America_Anguilla,
  @JsonValue(r'America/Antigua')
  America_Antigua,
  @JsonValue(r'America/Araguaina')
  America_Araguaina,
  @JsonValue(r'America/Argentina/Buenos_Aires')
  America_Argentina_Buenos_Aires,
  @JsonValue(r'America/Argentina/Catamarca')
  America_Argentina_Catamarca,
  @JsonValue(r'America/Argentina/ComodRivadavia')
  America_Argentina_ComodRivadavia,
  @JsonValue(r'America/Argentina/Cordoba')
  America_Argentina_Cordoba,
  @JsonValue(r'America/Argentina/Jujuy')
  America_Argentina_Jujuy,
  @JsonValue(r'America/Argentina/La_Rioja')
  America_Argentina_La_Rioja,
  @JsonValue(r'America/Argentina/Mendoza')
  America_Argentina_Mendoza,
  @JsonValue(r'America/Argentina/Rio_Gallegos')
  America_Argentina_Rio_Gallegos,
  @JsonValue(r'America/Argentina/Salta')
  America_Argentina_Salta,
  @JsonValue(r'America/Argentina/San_Juan')
  America_Argentina_San_Juan,
  @JsonValue(r'America/Argentina/San_Luis')
  America_Argentina_San_Luis,
  @JsonValue(r'America/Argentina/Tucuman')
  America_Argentina_Tucuman,
  @JsonValue(r'America/Argentina/Ushuaia')
  America_Argentina_Ushuaia,
  @JsonValue(r'America/Aruba')
  America_Aruba,
  @JsonValue(r'America/Asuncion')
  America_Asuncion,
  @JsonValue(r'America/Atikokan')
  America_Atikokan,
  @JsonValue(r'America/Atka')
  America_Atka,
  @JsonValue(r'America/Bahia')
  America_Bahia,
  @JsonValue(r'America/Bahia_Banderas')
  America_Bahia_Banderas,
  @JsonValue(r'America/Barbados')
  America_Barbados,
  @JsonValue(r'America/Belem')
  America_Belem,
  @JsonValue(r'America/Belize')
  America_Belize,
  @JsonValue(r'America/Blanc-Sablon')
  America_BlancMinusSablon,
  @JsonValue(r'America/Boa_Vista')
  America_Boa_Vista,
  @JsonValue(r'America/Bogota')
  America_Bogota,
  @JsonValue(r'America/Boise')
  America_Boise,
  @JsonValue(r'America/Buenos_Aires')
  America_Buenos_Aires,
  @JsonValue(r'America/Cambridge_Bay')
  America_Cambridge_Bay,
  @JsonValue(r'America/Campo_Grande')
  America_Campo_Grande,
  @JsonValue(r'America/Cancun')
  America_Cancun,
  @JsonValue(r'America/Caracas')
  America_Caracas,
  @JsonValue(r'America/Catamarca')
  America_Catamarca,
  @JsonValue(r'America/Cayenne')
  America_Cayenne,
  @JsonValue(r'America/Cayman')
  America_Cayman,
  @JsonValue(r'America/Chicago')
  America_Chicago,
  @JsonValue(r'America/Chihuahua')
  America_Chihuahua,
  @JsonValue(r'America/Coral_Harbour')
  America_Coral_Harbour,
  @JsonValue(r'America/Cordoba')
  America_Cordoba,
  @JsonValue(r'America/Costa_Rica')
  America_Costa_Rica,
  @JsonValue(r'America/Creston')
  America_Creston,
  @JsonValue(r'America/Cuiaba')
  America_Cuiaba,
  @JsonValue(r'America/Curacao')
  America_Curacao,
  @JsonValue(r'America/Danmarkshavn')
  America_Danmarkshavn,
  @JsonValue(r'America/Dawson')
  America_Dawson,
  @JsonValue(r'America/Dawson_Creek')
  America_Dawson_Creek,
  @JsonValue(r'America/Denver')
  America_Denver,
  @JsonValue(r'America/Detroit')
  America_Detroit,
  @JsonValue(r'America/Dominica')
  America_Dominica,
  @JsonValue(r'America/Edmonton')
  America_Edmonton,
  @JsonValue(r'America/Eirunepe')
  America_Eirunepe,
  @JsonValue(r'America/El_Salvador')
  America_El_Salvador,
  @JsonValue(r'America/Ensenada')
  America_Ensenada,
  @JsonValue(r'America/Fort_Nelson')
  America_Fort_Nelson,
  @JsonValue(r'America/Fort_Wayne')
  America_Fort_Wayne,
  @JsonValue(r'America/Fortaleza')
  America_Fortaleza,
  @JsonValue(r'America/Glace_Bay')
  America_Glace_Bay,
  @JsonValue(r'America/Godthab')
  America_Godthab,
  @JsonValue(r'America/Goose_Bay')
  America_Goose_Bay,
  @JsonValue(r'America/Grand_Turk')
  America_Grand_Turk,
  @JsonValue(r'America/Grenada')
  America_Grenada,
  @JsonValue(r'America/Guadeloupe')
  America_Guadeloupe,
  @JsonValue(r'America/Guatemala')
  America_Guatemala,
  @JsonValue(r'America/Guayaquil')
  America_Guayaquil,
  @JsonValue(r'America/Guyana')
  America_Guyana,
  @JsonValue(r'America/Halifax')
  America_Halifax,
  @JsonValue(r'America/Havana')
  America_Havana,
  @JsonValue(r'America/Hermosillo')
  America_Hermosillo,
  @JsonValue(r'America/Indiana/Indianapolis')
  America_Indiana_Indianapolis,
  @JsonValue(r'America/Indiana/Knox')
  America_Indiana_Knox,
  @JsonValue(r'America/Indiana/Marengo')
  America_Indiana_Marengo,
  @JsonValue(r'America/Indiana/Petersburg')
  America_Indiana_Petersburg,
  @JsonValue(r'America/Indiana/Tell_City')
  America_Indiana_Tell_City,
  @JsonValue(r'America/Indiana/Vevay')
  America_Indiana_Vevay,
  @JsonValue(r'America/Indiana/Vincennes')
  America_Indiana_Vincennes,
  @JsonValue(r'America/Indiana/Winamac')
  America_Indiana_Winamac,
  @JsonValue(r'America/Indianapolis')
  America_Indianapolis,
  @JsonValue(r'America/Inuvik')
  America_Inuvik,
  @JsonValue(r'America/Iqaluit')
  America_Iqaluit,
  @JsonValue(r'America/Jamaica')
  America_Jamaica,
  @JsonValue(r'America/Jujuy')
  America_Jujuy,
  @JsonValue(r'America/Juneau')
  America_Juneau,
  @JsonValue(r'America/Kentucky/Louisville')
  America_Kentucky_Louisville,
  @JsonValue(r'America/Kentucky/Monticello')
  America_Kentucky_Monticello,
  @JsonValue(r'America/Knox_IN')
  America_Knox_IN,
  @JsonValue(r'America/Kralendijk')
  America_Kralendijk,
  @JsonValue(r'America/La_Paz')
  America_La_Paz,
  @JsonValue(r'America/Lima')
  America_Lima,
  @JsonValue(r'America/Los_Angeles')
  America_Los_Angeles,
  @JsonValue(r'America/Louisville')
  America_Louisville,
  @JsonValue(r'America/Lower_Princes')
  America_Lower_Princes,
  @JsonValue(r'America/Maceio')
  America_Maceio,
  @JsonValue(r'America/Managua')
  America_Managua,
  @JsonValue(r'America/Manaus')
  America_Manaus,
  @JsonValue(r'America/Marigot')
  America_Marigot,
  @JsonValue(r'America/Martinique')
  America_Martinique,
  @JsonValue(r'America/Matamoros')
  America_Matamoros,
  @JsonValue(r'America/Mazatlan')
  America_Mazatlan,
  @JsonValue(r'America/Mendoza')
  America_Mendoza,
  @JsonValue(r'America/Menominee')
  America_Menominee,
  @JsonValue(r'America/Merida')
  America_Merida,
  @JsonValue(r'America/Metlakatla')
  America_Metlakatla,
  @JsonValue(r'America/Mexico_City')
  America_Mexico_City,
  @JsonValue(r'America/Miquelon')
  America_Miquelon,
  @JsonValue(r'America/Moncton')
  America_Moncton,
  @JsonValue(r'America/Monterrey')
  America_Monterrey,
  @JsonValue(r'America/Montevideo')
  America_Montevideo,
  @JsonValue(r'America/Montreal')
  America_Montreal,
  @JsonValue(r'America/Montserrat')
  America_Montserrat,
  @JsonValue(r'America/Nassau')
  America_Nassau,
  @JsonValue(r'America/New_York')
  America_New_York,
  @JsonValue(r'America/Nipigon')
  America_Nipigon,
  @JsonValue(r'America/Nome')
  America_Nome,
  @JsonValue(r'America/Noronha')
  America_Noronha,
  @JsonValue(r'America/North_Dakota/Beulah')
  America_North_Dakota_Beulah,
  @JsonValue(r'America/North_Dakota/Center')
  America_North_Dakota_Center,
  @JsonValue(r'America/North_Dakota/New_Salem')
  America_North_Dakota_New_Salem,
  @JsonValue(r'America/Ojinaga')
  America_Ojinaga,
  @JsonValue(r'America/Panama')
  America_Panama,
  @JsonValue(r'America/Pangnirtung')
  America_Pangnirtung,
  @JsonValue(r'America/Paramaribo')
  America_Paramaribo,
  @JsonValue(r'America/Phoenix')
  America_Phoenix,
  @JsonValue(r'America/Port-au-Prince')
  America_PortMinusauMinusPrince,
  @JsonValue(r'America/Port_of_Spain')
  America_Port_of_Spain,
  @JsonValue(r'America/Porto_Acre')
  America_Porto_Acre,
  @JsonValue(r'America/Porto_Velho')
  America_Porto_Velho,
  @JsonValue(r'America/Puerto_Rico')
  America_Puerto_Rico,
  @JsonValue(r'America/Rainy_River')
  America_Rainy_River,
  @JsonValue(r'America/Rankin_Inlet')
  America_Rankin_Inlet,
  @JsonValue(r'America/Recife')
  America_Recife,
  @JsonValue(r'America/Regina')
  America_Regina,
  @JsonValue(r'America/Resolute')
  America_Resolute,
  @JsonValue(r'America/Rio_Branco')
  America_Rio_Branco,
  @JsonValue(r'America/Rosario')
  America_Rosario,
  @JsonValue(r'America/Santa_Isabel')
  America_Santa_Isabel,
  @JsonValue(r'America/Santarem')
  America_Santarem,
  @JsonValue(r'America/Santiago')
  America_Santiago,
  @JsonValue(r'America/Santo_Domingo')
  America_Santo_Domingo,
  @JsonValue(r'America/Sao_Paulo')
  America_Sao_Paulo,
  @JsonValue(r'America/Scoresbysund')
  America_Scoresbysund,
  @JsonValue(r'America/Shiprock')
  America_Shiprock,
  @JsonValue(r'America/Sitka')
  America_Sitka,
  @JsonValue(r'America/St_Barthelemy')
  America_St_Barthelemy,
  @JsonValue(r'America/St_Johns')
  America_St_Johns,
  @JsonValue(r'America/St_Kitts')
  America_St_Kitts,
  @JsonValue(r'America/St_Lucia')
  America_St_Lucia,
  @JsonValue(r'America/St_Thomas')
  America_St_Thomas,
  @JsonValue(r'America/St_Vincent')
  America_St_Vincent,
  @JsonValue(r'America/Swift_Current')
  America_Swift_Current,
  @JsonValue(r'America/Tegucigalpa')
  America_Tegucigalpa,
  @JsonValue(r'America/Thule')
  America_Thule,
  @JsonValue(r'America/Thunder_Bay')
  America_Thunder_Bay,
  @JsonValue(r'America/Tijuana')
  America_Tijuana,
  @JsonValue(r'America/Toronto')
  America_Toronto,
  @JsonValue(r'America/Tortola')
  America_Tortola,
  @JsonValue(r'America/Vancouver')
  America_Vancouver,
  @JsonValue(r'America/Virgin')
  America_Virgin,
  @JsonValue(r'America/Whitehorse')
  America_Whitehorse,
  @JsonValue(r'America/Winnipeg')
  America_Winnipeg,
  @JsonValue(r'America/Yakutat')
  America_Yakutat,
  @JsonValue(r'America/Yellowknife')
  America_Yellowknife,
  @JsonValue(r'Antarctica/Casey')
  Antarctica_Casey,
  @JsonValue(r'Antarctica/Davis')
  Antarctica_Davis,
  @JsonValue(r'Antarctica/DumontDUrville')
  Antarctica_DumontDUrville,
  @JsonValue(r'Antarctica/Macquarie')
  Antarctica_Macquarie,
  @JsonValue(r'Antarctica/Mawson')
  Antarctica_Mawson,
  @JsonValue(r'Antarctica/McMurdo')
  Antarctica_McMurdo,
  @JsonValue(r'Antarctica/Palmer')
  Antarctica_Palmer,
  @JsonValue(r'Antarctica/Rothera')
  Antarctica_Rothera,
  @JsonValue(r'Antarctica/South_Pole')
  Antarctica_South_Pole,
  @JsonValue(r'Antarctica/Syowa')
  Antarctica_Syowa,
  @JsonValue(r'Antarctica/Troll')
  Antarctica_Troll,
  @JsonValue(r'Antarctica/Vostok')
  Antarctica_Vostok,
  @JsonValue(r'Arctic/Longyearbyen')
  Arctic_Longyearbyen,
  @JsonValue(r'Asia/Aden')
  Asia_Aden,
  @JsonValue(r'Asia/Almaty')
  Asia_Almaty,
  @JsonValue(r'Asia/Amman')
  Asia_Amman,
  @JsonValue(r'Asia/Anadyr')
  Asia_Anadyr,
  @JsonValue(r'Asia/Aqtau')
  Asia_Aqtau,
  @JsonValue(r'Asia/Aqtobe')
  Asia_Aqtobe,
  @JsonValue(r'Asia/Ashgabat')
  Asia_Ashgabat,
  @JsonValue(r'Asia/Ashkhabad')
  Asia_Ashkhabad,
  @JsonValue(r'Asia/Atyrau')
  Asia_Atyrau,
  @JsonValue(r'Asia/Baghdad')
  Asia_Baghdad,
  @JsonValue(r'Asia/Bahrain')
  Asia_Bahrain,
  @JsonValue(r'Asia/Baku')
  Asia_Baku,
  @JsonValue(r'Asia/Bangkok')
  Asia_Bangkok,
  @JsonValue(r'Asia/Barnaul')
  Asia_Barnaul,
  @JsonValue(r'Asia/Beirut')
  Asia_Beirut,
  @JsonValue(r'Asia/Bishkek')
  Asia_Bishkek,
  @JsonValue(r'Asia/Brunei')
  Asia_Brunei,
  @JsonValue(r'Asia/Calcutta')
  Asia_Calcutta,
  @JsonValue(r'Asia/Chita')
  Asia_Chita,
  @JsonValue(r'Asia/Choibalsan')
  Asia_Choibalsan,
  @JsonValue(r'Asia/Chongqing')
  Asia_Chongqing,
  @JsonValue(r'Asia/Chungking')
  Asia_Chungking,
  @JsonValue(r'Asia/Colombo')
  Asia_Colombo,
  @JsonValue(r'Asia/Dacca')
  Asia_Dacca,
  @JsonValue(r'Asia/Damascus')
  Asia_Damascus,
  @JsonValue(r'Asia/Dhaka')
  Asia_Dhaka,
  @JsonValue(r'Asia/Dili')
  Asia_Dili,
  @JsonValue(r'Asia/Dubai')
  Asia_Dubai,
  @JsonValue(r'Asia/Dushanbe')
  Asia_Dushanbe,
  @JsonValue(r'Asia/Famagusta')
  Asia_Famagusta,
  @JsonValue(r'Asia/Gaza')
  Asia_Gaza,
  @JsonValue(r'Asia/Hanoi')
  Asia_Hanoi,
  @JsonValue(r'Asia/Harbin')
  Asia_Harbin,
  @JsonValue(r'Asia/Hebron')
  Asia_Hebron,
  @JsonValue(r'Asia/Ho_Chi_Minh')
  Asia_Ho_Chi_Minh,
  @JsonValue(r'Asia/Hong_Kong')
  Asia_Hong_Kong,
  @JsonValue(r'Asia/Hovd')
  Asia_Hovd,
  @JsonValue(r'Asia/Irkutsk')
  Asia_Irkutsk,
  @JsonValue(r'Asia/Istanbul')
  Asia_Istanbul,
  @JsonValue(r'Asia/Jakarta')
  Asia_Jakarta,
  @JsonValue(r'Asia/Jayapura')
  Asia_Jayapura,
  @JsonValue(r'Asia/Jerusalem')
  Asia_Jerusalem,
  @JsonValue(r'Asia/Kabul')
  Asia_Kabul,
  @JsonValue(r'Asia/Kamchatka')
  Asia_Kamchatka,
  @JsonValue(r'Asia/Karachi')
  Asia_Karachi,
  @JsonValue(r'Asia/Kashgar')
  Asia_Kashgar,
  @JsonValue(r'Asia/Kathmandu')
  Asia_Kathmandu,
  @JsonValue(r'Asia/Katmandu')
  Asia_Katmandu,
  @JsonValue(r'Asia/Khandyga')
  Asia_Khandyga,
  @JsonValue(r'Asia/Kolkata')
  Asia_Kolkata,
  @JsonValue(r'Asia/Krasnoyarsk')
  Asia_Krasnoyarsk,
  @JsonValue(r'Asia/Kuala_Lumpur')
  Asia_Kuala_Lumpur,
  @JsonValue(r'Asia/Kuching')
  Asia_Kuching,
  @JsonValue(r'Asia/Kuwait')
  Asia_Kuwait,
  @JsonValue(r'Asia/Macao')
  Asia_Macao,
  @JsonValue(r'Asia/Macau')
  Asia_Macau,
  @JsonValue(r'Asia/Magadan')
  Asia_Magadan,
  @JsonValue(r'Asia/Makassar')
  Asia_Makassar,
  @JsonValue(r'Asia/Manila')
  Asia_Manila,
  @JsonValue(r'Asia/Muscat')
  Asia_Muscat,
  @JsonValue(r'Asia/Nicosia')
  Asia_Nicosia,
  @JsonValue(r'Asia/Novokuznetsk')
  Asia_Novokuznetsk,
  @JsonValue(r'Asia/Novosibirsk')
  Asia_Novosibirsk,
  @JsonValue(r'Asia/Omsk')
  Asia_Omsk,
  @JsonValue(r'Asia/Oral')
  Asia_Oral,
  @JsonValue(r'Asia/Phnom_Penh')
  Asia_Phnom_Penh,
  @JsonValue(r'Asia/Pontianak')
  Asia_Pontianak,
  @JsonValue(r'Asia/Pyongyang')
  Asia_Pyongyang,
  @JsonValue(r'Asia/Qatar')
  Asia_Qatar,
  @JsonValue(r'Asia/Qyzylorda')
  Asia_Qyzylorda,
  @JsonValue(r'Asia/Rangoon')
  Asia_Rangoon,
  @JsonValue(r'Asia/Riyadh')
  Asia_Riyadh,
  @JsonValue(r'Asia/Saigon')
  Asia_Saigon,
  @JsonValue(r'Asia/Sakhalin')
  Asia_Sakhalin,
  @JsonValue(r'Asia/Samarkand')
  Asia_Samarkand,
  @JsonValue(r'Asia/Seoul')
  Asia_Seoul,
  @JsonValue(r'Asia/Shanghai')
  Asia_Shanghai,
  @JsonValue(r'Asia/Singapore')
  Asia_Singapore,
  @JsonValue(r'Asia/Srednekolymsk')
  Asia_Srednekolymsk,
  @JsonValue(r'Asia/Taipei')
  Asia_Taipei,
  @JsonValue(r'Asia/Tashkent')
  Asia_Tashkent,
  @JsonValue(r'Asia/Tbilisi')
  Asia_Tbilisi,
  @JsonValue(r'Asia/Tehran')
  Asia_Tehran,
  @JsonValue(r'Asia/Tel_Aviv')
  Asia_Tel_Aviv,
  @JsonValue(r'Asia/Thimbu')
  Asia_Thimbu,
  @JsonValue(r'Asia/Thimphu')
  Asia_Thimphu,
  @JsonValue(r'Asia/Tokyo')
  Asia_Tokyo,
  @JsonValue(r'Asia/Tomsk')
  Asia_Tomsk,
  @JsonValue(r'Asia/Ujung_Pandang')
  Asia_Ujung_Pandang,
  @JsonValue(r'Asia/Ulaanbaatar')
  Asia_Ulaanbaatar,
  @JsonValue(r'Asia/Ulan_Bator')
  Asia_Ulan_Bator,
  @JsonValue(r'Asia/Urumqi')
  Asia_Urumqi,
  @JsonValue(r'Asia/Ust-Nera')
  Asia_UstMinusNera,
  @JsonValue(r'Asia/Vientiane')
  Asia_Vientiane,
  @JsonValue(r'Asia/Vladivostok')
  Asia_Vladivostok,
  @JsonValue(r'Asia/Yakutsk')
  Asia_Yakutsk,
  @JsonValue(r'Asia/Yangon')
  Asia_Yangon,
  @JsonValue(r'Asia/Yekaterinburg')
  Asia_Yekaterinburg,
  @JsonValue(r'Asia/Yerevan')
  Asia_Yerevan,
  @JsonValue(r'Atlantic/Azores')
  Atlantic_Azores,
  @JsonValue(r'Atlantic/Bermuda')
  Atlantic_Bermuda,
  @JsonValue(r'Atlantic/Canary')
  Atlantic_Canary,
  @JsonValue(r'Atlantic/Cape_Verde')
  Atlantic_Cape_Verde,
  @JsonValue(r'Atlantic/Faeroe')
  Atlantic_Faeroe,
  @JsonValue(r'Atlantic/Faroe')
  Atlantic_Faroe,
  @JsonValue(r'Atlantic/Jan_Mayen')
  Atlantic_Jan_Mayen,
  @JsonValue(r'Atlantic/Madeira')
  Atlantic_Madeira,
  @JsonValue(r'Atlantic/Reykjavik')
  Atlantic_Reykjavik,
  @JsonValue(r'Atlantic/South_Georgia')
  Atlantic_South_Georgia,
  @JsonValue(r'Atlantic/St_Helena')
  Atlantic_St_Helena,
  @JsonValue(r'Atlantic/Stanley')
  Atlantic_Stanley,
  @JsonValue(r'Australia/ACT')
  Australia_ACT,
  @JsonValue(r'Australia/Adelaide')
  Australia_Adelaide,
  @JsonValue(r'Australia/Brisbane')
  Australia_Brisbane,
  @JsonValue(r'Australia/Broken_Hill')
  Australia_Broken_Hill,
  @JsonValue(r'Australia/Canberra')
  Australia_Canberra,
  @JsonValue(r'Australia/Currie')
  Australia_Currie,
  @JsonValue(r'Australia/Darwin')
  Australia_Darwin,
  @JsonValue(r'Australia/Eucla')
  Australia_Eucla,
  @JsonValue(r'Australia/Hobart')
  Australia_Hobart,
  @JsonValue(r'Australia/LHI')
  Australia_LHI,
  @JsonValue(r'Australia/Lindeman')
  Australia_Lindeman,
  @JsonValue(r'Australia/Lord_Howe')
  Australia_Lord_Howe,
  @JsonValue(r'Australia/Melbourne')
  Australia_Melbourne,
  @JsonValue(r'Australia/NSW')
  Australia_NSW,
  @JsonValue(r'Australia/North')
  Australia_North,
  @JsonValue(r'Australia/Perth')
  Australia_Perth,
  @JsonValue(r'Australia/Queensland')
  Australia_Queensland,
  @JsonValue(r'Australia/South')
  Australia_South,
  @JsonValue(r'Australia/Sydney')
  Australia_Sydney,
  @JsonValue(r'Australia/Tasmania')
  Australia_Tasmania,
  @JsonValue(r'Australia/Victoria')
  Australia_Victoria,
  @JsonValue(r'Australia/West')
  Australia_West,
  @JsonValue(r'Australia/Yancowinna')
  Australia_Yancowinna,
  @JsonValue(r'Brazil/Acre')
  Brazil_Acre,
  @JsonValue(r'Brazil/DeNoronha')
  Brazil_DeNoronha,
  @JsonValue(r'Brazil/East')
  Brazil_East,
  @JsonValue(r'Brazil/West')
  Brazil_West,
  @JsonValue(r'CET')
  CET,
  @JsonValue(r'CST6CDT')
  CST6CDT,
  @JsonValue(r'Canada/Atlantic')
  Canada_Atlantic,
  @JsonValue(r'Canada/Central')
  Canada_Central,
  @JsonValue(r'Canada/East-Saskatchewan')
  Canada_EastMinusSaskatchewan,
  @JsonValue(r'Canada/Eastern')
  Canada_Eastern,
  @JsonValue(r'Canada/Mountain')
  Canada_Mountain,
  @JsonValue(r'Canada/Newfoundland')
  Canada_Newfoundland,
  @JsonValue(r'Canada/Pacific')
  Canada_Pacific,
  @JsonValue(r'Canada/Saskatchewan')
  Canada_Saskatchewan,
  @JsonValue(r'Canada/Yukon')
  Canada_Yukon,
  @JsonValue(r'Chile/Continental')
  Chile_Continental,
  @JsonValue(r'Chile/EasterIsland')
  Chile_EasterIsland,
  @JsonValue(r'Cuba')
  Cuba,
  @JsonValue(r'EET')
  EET,
  @JsonValue(r'EST')
  EST,
  @JsonValue(r'EST5EDT')
  EST5EDT,
  @JsonValue(r'Egypt')
  Egypt,
  @JsonValue(r'Eire')
  Eire,
  @JsonValue(r'Etc/GMT')
  Etc_GMT,
  @JsonValue(r'Etc/GMT+0')
  Etc_GMTPlus0,
  @JsonValue(r'Etc/GMT+1')
  Etc_GMTPlus1,
  @JsonValue(r'Etc/GMT+10')
  Etc_GMTPlus10,
  @JsonValue(r'Etc/GMT+11')
  Etc_GMTPlus11,
  @JsonValue(r'Etc/GMT+12')
  Etc_GMTPlus12,
  @JsonValue(r'Etc/GMT+2')
  Etc_GMTPlus2,
  @JsonValue(r'Etc/GMT+3')
  Etc_GMTPlus3,
  @JsonValue(r'Etc/GMT+4')
  Etc_GMTPlus4,
  @JsonValue(r'Etc/GMT+5')
  Etc_GMTPlus5,
  @JsonValue(r'Etc/GMT+6')
  Etc_GMTPlus6,
  @JsonValue(r'Etc/GMT+7')
  Etc_GMTPlus7,
  @JsonValue(r'Etc/GMT+8')
  Etc_GMTPlus8,
  @JsonValue(r'Etc/GMT+9')
  Etc_GMTPlus9,
  @JsonValue(r'Etc/GMT-0')
  Etc_GMTMinus0,
  @JsonValue(r'Etc/GMT-1')
  Etc_GMTMinus1,
  @JsonValue(r'Etc/GMT-10')
  Etc_GMTMinus10,
  @JsonValue(r'Etc/GMT-11')
  Etc_GMTMinus11,
  @JsonValue(r'Etc/GMT-12')
  Etc_GMTMinus12,
  @JsonValue(r'Etc/GMT-13')
  Etc_GMTMinus13,
  @JsonValue(r'Etc/GMT-14')
  Etc_GMTMinus14,
  @JsonValue(r'Etc/GMT-2')
  Etc_GMTMinus2,
  @JsonValue(r'Etc/GMT-3')
  Etc_GMTMinus3,
  @JsonValue(r'Etc/GMT-4')
  Etc_GMTMinus4,
  @JsonValue(r'Etc/GMT-5')
  Etc_GMTMinus5,
  @JsonValue(r'Etc/GMT-6')
  Etc_GMTMinus6,
  @JsonValue(r'Etc/GMT-7')
  Etc_GMTMinus7,
  @JsonValue(r'Etc/GMT-8')
  Etc_GMTMinus8,
  @JsonValue(r'Etc/GMT-9')
  Etc_GMTMinus9,
  @JsonValue(r'Etc/GMT0')
  Etc_GMT0,
  @JsonValue(r'Etc/Greenwich')
  Etc_Greenwich,
  @JsonValue(r'Etc/UCT')
  Etc_UCT,
  @JsonValue(r'Etc/UTC')
  Etc_UTC,
  @JsonValue(r'Etc/Universal')
  Etc_Universal,
  @JsonValue(r'Etc/Zulu')
  Etc_Zulu,
  @JsonValue(r'Europe/Amsterdam')
  Europe_Amsterdam,
  @JsonValue(r'Europe/Andorra')
  Europe_Andorra,
  @JsonValue(r'Europe/Astrakhan')
  Europe_Astrakhan,
  @JsonValue(r'Europe/Athens')
  Europe_Athens,
  @JsonValue(r'Europe/Belfast')
  Europe_Belfast,
  @JsonValue(r'Europe/Belgrade')
  Europe_Belgrade,
  @JsonValue(r'Europe/Berlin')
  Europe_Berlin,
  @JsonValue(r'Europe/Bratislava')
  Europe_Bratislava,
  @JsonValue(r'Europe/Brussels')
  Europe_Brussels,
  @JsonValue(r'Europe/Bucharest')
  Europe_Bucharest,
  @JsonValue(r'Europe/Budapest')
  Europe_Budapest,
  @JsonValue(r'Europe/Busingen')
  Europe_Busingen,
  @JsonValue(r'Europe/Chisinau')
  Europe_Chisinau,
  @JsonValue(r'Europe/Copenhagen')
  Europe_Copenhagen,
  @JsonValue(r'Europe/Dublin')
  Europe_Dublin,
  @JsonValue(r'Europe/Gibraltar')
  Europe_Gibraltar,
  @JsonValue(r'Europe/Guernsey')
  Europe_Guernsey,
  @JsonValue(r'Europe/Helsinki')
  Europe_Helsinki,
  @JsonValue(r'Europe/Isle_of_Man')
  Europe_Isle_of_Man,
  @JsonValue(r'Europe/Istanbul')
  Europe_Istanbul,
  @JsonValue(r'Europe/Jersey')
  Europe_Jersey,
  @JsonValue(r'Europe/Kaliningrad')
  Europe_Kaliningrad,
  @JsonValue(r'Europe/Kiev')
  Europe_Kiev,
  @JsonValue(r'Europe/Kirov')
  Europe_Kirov,
  @JsonValue(r'Europe/Lisbon')
  Europe_Lisbon,
  @JsonValue(r'Europe/Ljubljana')
  Europe_Ljubljana,
  @JsonValue(r'Europe/London')
  Europe_London,
  @JsonValue(r'Europe/Luxembourg')
  Europe_Luxembourg,
  @JsonValue(r'Europe/Madrid')
  Europe_Madrid,
  @JsonValue(r'Europe/Malta')
  Europe_Malta,
  @JsonValue(r'Europe/Mariehamn')
  Europe_Mariehamn,
  @JsonValue(r'Europe/Minsk')
  Europe_Minsk,
  @JsonValue(r'Europe/Monaco')
  Europe_Monaco,
  @JsonValue(r'Europe/Moscow')
  Europe_Moscow,
  @JsonValue(r'Europe/Nicosia')
  Europe_Nicosia,
  @JsonValue(r'Europe/Oslo')
  Europe_Oslo,
  @JsonValue(r'Europe/Paris')
  Europe_Paris,
  @JsonValue(r'Europe/Podgorica')
  Europe_Podgorica,
  @JsonValue(r'Europe/Prague')
  Europe_Prague,
  @JsonValue(r'Europe/Riga')
  Europe_Riga,
  @JsonValue(r'Europe/Rome')
  Europe_Rome,
  @JsonValue(r'Europe/Samara')
  Europe_Samara,
  @JsonValue(r'Europe/San_Marino')
  Europe_San_Marino,
  @JsonValue(r'Europe/Sarajevo')
  Europe_Sarajevo,
  @JsonValue(r'Europe/Saratov')
  Europe_Saratov,
  @JsonValue(r'Europe/Simferopol')
  Europe_Simferopol,
  @JsonValue(r'Europe/Skopje')
  Europe_Skopje,
  @JsonValue(r'Europe/Sofia')
  Europe_Sofia,
  @JsonValue(r'Europe/Stockholm')
  Europe_Stockholm,
  @JsonValue(r'Europe/Tallinn')
  Europe_Tallinn,
  @JsonValue(r'Europe/Tirane')
  Europe_Tirane,
  @JsonValue(r'Europe/Tiraspol')
  Europe_Tiraspol,
  @JsonValue(r'Europe/Ulyanovsk')
  Europe_Ulyanovsk,
  @JsonValue(r'Europe/Uzhgorod')
  Europe_Uzhgorod,
  @JsonValue(r'Europe/Vaduz')
  Europe_Vaduz,
  @JsonValue(r'Europe/Vatican')
  Europe_Vatican,
  @JsonValue(r'Europe/Vienna')
  Europe_Vienna,
  @JsonValue(r'Europe/Vilnius')
  Europe_Vilnius,
  @JsonValue(r'Europe/Volgograd')
  Europe_Volgograd,
  @JsonValue(r'Europe/Warsaw')
  Europe_Warsaw,
  @JsonValue(r'Europe/Zagreb')
  Europe_Zagreb,
  @JsonValue(r'Europe/Zaporozhye')
  Europe_Zaporozhye,
  @JsonValue(r'Europe/Zurich')
  Europe_Zurich,
  @JsonValue(r'GB')
  GB,
  @JsonValue(r'GB-Eire')
  GBMinusEire,
  @JsonValue(r'GMT')
  GMT,
  @JsonValue(r'GMT+0')
  GMTPlus0,
  @JsonValue(r'GMT-0')
  GMTMinus0,
  @JsonValue(r'GMT0')
  GMT0,
  @JsonValue(r'Greenwich')
  Greenwich,
  @JsonValue(r'HST')
  HST,
  @JsonValue(r'Hongkong')
  Hongkong,
  @JsonValue(r'Iceland')
  Iceland,
  @JsonValue(r'Indian/Antananarivo')
  Indian_Antananarivo,
  @JsonValue(r'Indian/Chagos')
  Indian_Chagos,
  @JsonValue(r'Indian/Christmas')
  Indian_Christmas,
  @JsonValue(r'Indian/Cocos')
  Indian_Cocos,
  @JsonValue(r'Indian/Comoro')
  Indian_Comoro,
  @JsonValue(r'Indian/Kerguelen')
  Indian_Kerguelen,
  @JsonValue(r'Indian/Mahe')
  Indian_Mahe,
  @JsonValue(r'Indian/Maldives')
  Indian_Maldives,
  @JsonValue(r'Indian/Mauritius')
  Indian_Mauritius,
  @JsonValue(r'Indian/Mayotte')
  Indian_Mayotte,
  @JsonValue(r'Indian/Reunion')
  Indian_Reunion,
  @JsonValue(r'Iran')
  Iran,
  @JsonValue(r'Israel')
  Israel,
  @JsonValue(r'Jamaica')
  Jamaica,
  @JsonValue(r'Japan')
  Japan,
  @JsonValue(r'Kwajalein')
  Kwajalein,
  @JsonValue(r'Libya')
  Libya,
  @JsonValue(r'MET')
  MET,
  @JsonValue(r'MST')
  MST,
  @JsonValue(r'MST7MDT')
  MST7MDT,
  @JsonValue(r'Mexico/BajaNorte')
  Mexico_BajaNorte,
  @JsonValue(r'Mexico/BajaSur')
  Mexico_BajaSur,
  @JsonValue(r'Mexico/General')
  Mexico_General,
  @JsonValue(r'NZ')
  NZ,
  @JsonValue(r'NZ-CHAT')
  NZMinusCHAT,
  @JsonValue(r'Navajo')
  Navajo,
  @JsonValue(r'PRC')
  PRC,
  @JsonValue(r'PST8PDT')
  PST8PDT,
  @JsonValue(r'Pacific/Apia')
  Pacific_Apia,
  @JsonValue(r'Pacific/Auckland')
  Pacific_Auckland,
  @JsonValue(r'Pacific/Bougainville')
  Pacific_Bougainville,
  @JsonValue(r'Pacific/Chatham')
  Pacific_Chatham,
  @JsonValue(r'Pacific/Chuuk')
  Pacific_Chuuk,
  @JsonValue(r'Pacific/Easter')
  Pacific_Easter,
  @JsonValue(r'Pacific/Efate')
  Pacific_Efate,
  @JsonValue(r'Pacific/Enderbury')
  Pacific_Enderbury,
  @JsonValue(r'Pacific/Fakaofo')
  Pacific_Fakaofo,
  @JsonValue(r'Pacific/Fiji')
  Pacific_Fiji,
  @JsonValue(r'Pacific/Funafuti')
  Pacific_Funafuti,
  @JsonValue(r'Pacific/Galapagos')
  Pacific_Galapagos,
  @JsonValue(r'Pacific/Gambier')
  Pacific_Gambier,
  @JsonValue(r'Pacific/Guadalcanal')
  Pacific_Guadalcanal,
  @JsonValue(r'Pacific/Guam')
  Pacific_Guam,
  @JsonValue(r'Pacific/Honolulu')
  Pacific_Honolulu,
  @JsonValue(r'Pacific/Johnston')
  Pacific_Johnston,
  @JsonValue(r'Pacific/Kiritimati')
  Pacific_Kiritimati,
  @JsonValue(r'Pacific/Kosrae')
  Pacific_Kosrae,
  @JsonValue(r'Pacific/Kwajalein')
  Pacific_Kwajalein,
  @JsonValue(r'Pacific/Majuro')
  Pacific_Majuro,
  @JsonValue(r'Pacific/Marquesas')
  Pacific_Marquesas,
  @JsonValue(r'Pacific/Midway')
  Pacific_Midway,
  @JsonValue(r'Pacific/Nauru')
  Pacific_Nauru,
  @JsonValue(r'Pacific/Niue')
  Pacific_Niue,
  @JsonValue(r'Pacific/Norfolk')
  Pacific_Norfolk,
  @JsonValue(r'Pacific/Noumea')
  Pacific_Noumea,
  @JsonValue(r'Pacific/Pago_Pago')
  Pacific_Pago_Pago,
  @JsonValue(r'Pacific/Palau')
  Pacific_Palau,
  @JsonValue(r'Pacific/Pitcairn')
  Pacific_Pitcairn,
  @JsonValue(r'Pacific/Pohnpei')
  Pacific_Pohnpei,
  @JsonValue(r'Pacific/Ponape')
  Pacific_Ponape,
  @JsonValue(r'Pacific/Port_Moresby')
  Pacific_Port_Moresby,
  @JsonValue(r'Pacific/Rarotonga')
  Pacific_Rarotonga,
  @JsonValue(r'Pacific/Saipan')
  Pacific_Saipan,
  @JsonValue(r'Pacific/Samoa')
  Pacific_Samoa,
  @JsonValue(r'Pacific/Tahiti')
  Pacific_Tahiti,
  @JsonValue(r'Pacific/Tarawa')
  Pacific_Tarawa,
  @JsonValue(r'Pacific/Tongatapu')
  Pacific_Tongatapu,
  @JsonValue(r'Pacific/Truk')
  Pacific_Truk,
  @JsonValue(r'Pacific/Wake')
  Pacific_Wake,
  @JsonValue(r'Pacific/Wallis')
  Pacific_Wallis,
  @JsonValue(r'Pacific/Yap')
  Pacific_Yap,
  @JsonValue(r'Poland')
  Poland,
  @JsonValue(r'Portugal')
  Portugal,
  @JsonValue(r'ROC')
  ROC,
  @JsonValue(r'ROK')
  ROK,
  @JsonValue(r'Singapore')
  Singapore,
  @JsonValue(r'Turkey')
  Turkey,
  @JsonValue(r'UCT')
  UCT,
  @JsonValue(r'US/Alaska')
  US_Alaska,
  @JsonValue(r'US/Aleutian')
  US_Aleutian,
  @JsonValue(r'US/Arizona')
  US_Arizona,
  @JsonValue(r'US/Central')
  US_Central,
  @JsonValue(r'US/East-Indiana')
  US_EastMinusIndiana,
  @JsonValue(r'US/Eastern')
  US_Eastern,
  @JsonValue(r'US/Hawaii')
  US_Hawaii,
  @JsonValue(r'US/Indiana-Starke')
  US_IndianaMinusStarke,
  @JsonValue(r'US/Michigan')
  US_Michigan,
  @JsonValue(r'US/Mountain')
  US_Mountain,
  @JsonValue(r'US/Pacific')
  US_Pacific,
  @JsonValue(r'US/Samoa')
  US_Samoa,
  @JsonValue(r'UTC')
  UTC,
  @JsonValue(r'Universal')
  Universal,
  @JsonValue(r'W-SU')
  WMinusSU,
  @JsonValue(r'WET')
  WET,
  @JsonValue(r'Zulu')
  Zulu,
}
